---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: database
spec:
  schedule: "0 1 * * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres
