kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:Qz3/yCff8LHWumcKmWeJ3Q==,iv:ljcmLKwe14B/crG99FsmytJxiNlu7TzDoihL/Tt4zjQ=,tag:Ge4ac8xRdODtJOtKObBTvQ==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:YzvOhl+5s5fyBZ3RXz9Rf/9sld5+3srfFQ/Ucg3Fkjk=,iv:1Q3IZxAOYWihf1wwd6ZeFZZin/qkF2MITPrhR7E93lw=,tag:6Srehi+7/H2Ta3gvuVXC9A==,type:str]
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: app-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:wI8REos=,iv:MueHBDblqo5f8ZUvJC4DaVwOHjyTWWQ0+2H18bwCJ1E=,tag:5IHoowF5vlP8SmMFaTii3Q==,type:str]
    password: ENC[AES256_GCM,data:pU2IeblS4hP6NIQGHdqBOJ4i,iv:uQTdXjKuOIY7vPdhOMMEREs03s0XY5ZhsNjgtBfNd/Q=,tag:gy/kEDq9xPRFg1G0p1IKWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T04:11:29Z"
    mac: ENC[AES256_GCM,data:ZNDsy+sIw7yGmnJ+Ee2DFlDpSvEkjQ4rMaJFQErBR2tsz7grkK+IFMNXaorfLcXjaI34ez51UZJEZ8lKxuM9nOYWPwKCij7ePxfEu8mowN/IJYXXXWajLKqm6wjqVP3reXjTvIelg3xGArVJmlocpvTEGOe3ERskDrSpRTmk8mc=,iv:R/bOl2YQbvE1kFtYvApmjH3UQX+uuUXxYdZhM7aPVNo=,tag:sMP0a1qOuiZNYBLntJRG7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
