apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:/gxfV/4NNRQ=,iv:bcRRwFX9Gx3qOUFV8kUBd2JQ/kgRZ4mjuk6+sbThvbw=,tag:lAD9diHqUkjj2Ms3lGO/sw==,type:str]
    password: ENC[AES256_GCM,data:PTpjPsK2Ruw5fVafjzsm+gbU,iv:fDeyEg1QZ/kJUYBym6JlFVvW5Kg0Lz47rBV/ub0rXyM=,tag:6ejnogStiGGGgIEPBubLkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T04:20:52Z"
    mac: ENC[AES256_GCM,data:R2jJmerxgv+7i3N9ZvACPbR7B6TsG23fG2QgGeG9Tklva3TOXJi9sROGXkXSM0AmXrM/xmP3qxU7KGqTTjTqXE1nb6g80p6Nl/CgACeDnT1HcTj/Kl9lPU4L8RdzHrQKVDq71v+Cim55nGAg/r/WvmDyuIYFFqecrB5aacaJByg=,iv:oVhhWwHuT1UB0s0SNvmOgEcbFTQgfjqs07HJ7jwvoI0=,tag:zYvWCaDKSrylEztjS78I+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:tHeq3bYwRZk=,iv:lnfICXKZyBLeArIIZGYaT3AIj7GWZAPeSi7Muw8xUhU=,tag:hs7tJk9wh2pvXgAjDkOeeA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:XNhGnoHn84iOqjrNpDglvWvVdO9dpZn1+d1hRGU61mKKGiG/DpM8Hg==,iv:88KdOBxdwxuOUb4pXKSbIelNcuGorT6KYCaE8FpVNCE=,tag:smcxcmzUdKDg7Prm+JThhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-20T04:20:52Z"
    mac: ENC[AES256_GCM,data:R2jJmerxgv+7i3N9ZvACPbR7B6TsG23fG2QgGeG9Tklva3TOXJi9sROGXkXSM0AmXrM/xmP3qxU7KGqTTjTqXE1nb6g80p6Nl/CgACeDnT1HcTj/Kl9lPU4L8RdzHrQKVDq71v+Cim55nGAg/r/WvmDyuIYFFqecrB5aacaJByg=,iv:oVhhWwHuT1UB0s0SNvmOgEcbFTQgfjqs07HJ7jwvoI0=,tag:zYvWCaDKSrylEztjS78I+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
