apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:Y4A=,iv:cwvHEJrk/QTqQ2cZZHGKPGNLdRRGCuN3GFFtikgx3g0=,tag:w+cG+M/uDnpqzkNA0NgX7g==,type:str]
    password: ENC[AES256_GCM,data:SH4B,iv:0+skA4YOa7jyQAz91NGPzlL17M1LuQDjWmpNpzRyalY=,tag:Q/KhF3W0anyG6d1tdFMyKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T04:20:44Z"
    mac: ENC[AES256_GCM,data:L9KJQ/5MB5pRXVdDye9FCwEkL9RJTJLGPQNYLYmI9MzQ/dbAFVFDUUpZS8FjBURyfPTrSKmy0tTzIXR8e3Qz34rCMvRqVH5Rs9tqLFSOVCjafSVwc4LoWduv8tzoi7RGMg4Xc3T/1RurM4ppmcf0+rJkogFQUqPcItK9EyRYakI=,iv:MqXhQksDOCFjMPryLGFwKqummtwqoBTzd5olhyOjC14=,tag:BjKRnWjx2TfYG99/MVnnsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:tHeq3bYwRZk=,iv:lnfICXKZyBLeArIIZGYaT3AIj7GWZAPeSi7Muw8xUhU=,tag:hs7tJk9wh2pvXgAjDkOeeA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:XNhGnoHn84iOqjrNpDglvWvVdO9dpZn1+d1hRGU61mKKGiG/DpM8Hg==,iv:88KdOBxdwxuOUb4pXKSbIelNcuGorT6KYCaE8FpVNCE=,tag:smcxcmzUdKDg7Prm+JThhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T04:20:44Z"
    mac: ENC[AES256_GCM,data:L9KJQ/5MB5pRXVdDye9FCwEkL9RJTJLGPQNYLYmI9MzQ/dbAFVFDUUpZS8FjBURyfPTrSKmy0tTzIXR8e3Qz34rCMvRqVH5Rs9tqLFSOVCjafSVwc4LoWduv8tzoi7RGMg4Xc3T/1RurM4ppmcf0+rJkogFQUqPcItK9EyRYakI=,iv:MqXhQksDOCFjMPryLGFwKqummtwqoBTzd5olhyOjC14=,tag:BjKRnWjx2TfYG99/MVnnsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
