apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:RHkXv8k6Vvc=,iv:LhEPoWUGArnpIt9XaoGHxXND02+7P6d7LyYqXOa45GU=,tag:0k90jX3DRh2r3AgLhVWJHQ==,type:str]
sops:
  age:
    - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWndYdlBkRUNHcmFvZHdL
        K2dHMjlZbFU3M0d1VExDbHNwa1B1TU9kN21RCm51b01WTGN5bjBQWGphcENPZmM1
        eTRxVE1wUk4rRms3bEZkcFp5TS8ycDQKLS0tIGxCQ2lEMXlzb0czT1N6N1dhL2Yw
        QUhzYnBhM3JxT2UySUhwN240UXlML1UKc2/2eDDqsbEYUNxhDCE7q4EaBIe66g09
        y3aV7zlK6dWDFRJkTpQG4h6vnG8J6otlu/4vMeQ8RdjlEjycZGz80A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-05T06:25:44Z"
  mac: ENC[AES256_GCM,data:EOydpdLySa5HbNBh7sv75y9ttshZH+cn/2bX2dhi7fToCpW2YTH62n4UPYpcolY+EV6hZMVsXNepTMUz1RdqqZ1xHGXabeAq/LuyV6F7BOOr2sxZgMAUsH/qJhOpreovtqdPhpQgp2LyNUyUXeerhZ5LiuzZDcleUgF5qortV6w=,iv:J84W5blyc3r7r2Q95ZIn0EMcsUgtLqHyRLZdwskmjLA=,tag:IQiv8El7+tOCLL+U8a8nkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
