---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.4.4@sha256:2582cc7e28849e4bdca8b991c3ede503ec706112d2eb2feb2191e9e980d37e92

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

    resources:
      requests:
        cpu: 5m
        memory: 12Mi
      limits:
        memory: 12Mi
