---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 8.0.1@sha256:1b7c17f650602d97a10724d796f45f0b5250d47ee5ba02f28de89f8a1531f3ce

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

    resources:
      requests:
        cpu: 5m
        memory: 12Mi
      limits:
        memory: 12Mi
