---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-redis
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: public.ecr.aws/docker/library/redis
      tag: 7.4.0@sha256:79676a8f74e4aed85b6d6a2f4e4e3e55d8a229baa7168362e592bbfdc67b0c9b

    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379

    resources:
      requests:
        cpu: 5m
        memory: 12Mi
      limits:
        memory: 12Mi
