apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: database
stringData:
    redis-password: ENC[AES256_GCM,data:wtkzwwc=,iv:Vu+mCGfZO6h0jkEd0AmLSPUL4Pn/BEhCsg8nh1ke/qM=,tag:7Uk/JV/j+jI+eE562MOeIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T20:26:24Z"
    mac: ENC[AES256_GCM,data:8xIXvyZRLwfR1QIE7knUm8u7BZjbM56YbSjI3gwuRWqPW6Un4Nic19fqM88qwGvnnblNT32L/H9p1bCxS4ZQtktukujK6SB2fJSNSscMWGE/G3wlftigvPBNW1RUKNybtb0iTM4pfnyOekeopd5wa5YATPeeVbfvjyLYRNLwuL8=,iv:u9qlpMd+p3IgEijhGakGtP9cZSCHsOo0uQ7hSY2EO8s=,tag:enONgur057xSXBEYWoMW0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
