apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis
    namespace: database
stringData:
    redis-password: ENC[AES256_GCM,data:wtkzwwc=,iv:Vu+mCGfZO6h0jkEd0AmLSPUL4Pn/BEhCsg8nh1ke/qM=,tag:7Uk/JV/j+jI+eE562MOeIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T04:09:45Z"
    mac: ENC[AES256_GCM,data:bOUrTyYazpHdMDGo5Tsy4K4OE+6tzMTDfhXTu0XXoNsOyoFFYOEsViFudBDXZi7PBcZ7kYe1L9powICa/LJnNV1fiMbFYwnM/vUqHANiPO4SdozzUuiULHMnZQqXplXSB2bU+2bdcFt5vHf6z3/B92JYbyHbR+yoSGU3l0WAjx0=,iv:LqFs3IZ1Y8BM3HXXFkXkOI8tTTAzR142LLw0j2T/Tkg=,tag:DHoYvcsWXQQmhhYXi+ULXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
