apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: redis
    namespace: default
stringData:
    redis-password: ENC[AES256_GCM,data:wtkzwwc=,iv:Vu+mCGfZO6h0jkEd0AmLSPUL4Pn/BEhCsg8nh1ke/qM=,tag:7Uk/JV/j+jI+eE562MOeIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T05:32:39Z"
    mac: ENC[AES256_GCM,data:O4OEaFsryAdrD0zUiPQX+7bfqUyMaCS+eJy/tR7xJRlqbixG73q4Pjw9Pz7gC5Tajs3B79OKXrg/cOwnQU8S16B/1dwPwI2lJY5X4JD8UL1Ykw5bHT2lnV3qRgrHF5xSsIMXbvrVp4p1xQjoBhEbJbJ/D/SFSYukrYV+xXRehgQ=,iv:dAeM27oIX1abVhh+PO5cGltwWWwwdC4rtSrjig5OiPs=,tag:W8/4gEmQI58JfuEPVjSdJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
