---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.12.2
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    toolbox:
      enabled: true

    ingress:
      dashboard:
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: content-save
          hajimari.io/appName: "rook-ceph"

        host:
          name: &host "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - *host

    monitoring:
      enabled: true
      createPrometheusRules: true

    configOverride: |
          [global]
          bdev_enable_discard = true
          bdev_async_discard = true

    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false

      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "worker-0"
            devices:
              - name: "/dev/sdb"
          - name: "worker-1"
            devices:
              - name: "/dev/sdb"
          - name: "worker-2"
            devices:
              - name: "/dev/sdb"

      resources:
        mgr:
          requests:
            cpu: "125m"
            memory: "549M"
          limits:
            memory: "1219M"
        mon:
          requests:
            cpu: "49m"
            memory: "477M"
          limits:
            memory: "1059M"
        osd:
          requests:
            cpu: "442m"
            memory: "2678M"
          limits:
            memory: "5944M"
        mgr-sidecar:
          requests:
            cpu: "49m"
            memory: "94M"
          limits:
            memory: "208M"
        crashcollector:
          requests:
            cpu: "15m"
            memory: "64M"
          limits:
            memory: "64M"
        logcollector:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            memory: "1G"
        cleanup:
          requests:
            cpu: "250m"
            memory: "100M"
          limits:
            memory: "1G"
    cephBlockPoolsVolumeSnapshotClass:
      enabled: false
      name: csi-rbdplugin-snapclass
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
        velero.io/csi-volumesnapshot-class: "true"