---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.13.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    toolbox:
      enabled: false

    ingress:
      ingressClassName: "internal"
      dashboard:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: content-save
          hajimari.io/appName: "rook-ceph"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

        host:
          name: &host "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - *host

    monitoring:
      enabled: true
      createPrometheusRules: true

    configOverride: |
          [global]
          bdev_enable_discard = true
          bdev_async_discard = true

    cephClusterSpec:
      network:
        provider: host

      crashCollector:
        disable: false

      dashboard:
        enabled: true
        urlPrefix: /


      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "node1"
            devices:
              - name: "/dev/sdb"
          - name: "node2"
            devices:
              - name: "/dev/sdb"
          - name: "node3"
            devices:
              - name: "/dev/sdb"

      resources:
        mgr:
          requests:
            # @default cpu 600m
            cpu: 125m
            memory: 100Mi
        mgr-sidecar:
          # @default cpu 600m
          requests:
            cpu: 50m
            memory: 50Mi
        mon:
          requests:
            # @default cpu 1000m
            cpu: 49m
            memory: 256Mi
        osd:
          requests:
            # @default cpu 3000m
            cpu: 300m
            memory: 512Mi
        prepareosd:
          requests:
            # @default cpu 3000m
            cpu: 100m

      # placement:
      #   all:
      #     tolerations:
      #       - effect: NoSchedule
      #         operator: Exists
      #       - effect: NoExecute
      # resources:
      #   mgr:
      #     requests:
      #       cpu: "125m"
      #       memory: "549M"
      #     limits:
      #       memory: "1219M"
      #   mon:
      #     requests:
      #       cpu: "49m"
      #       memory: "477M"
      #     limits:
      #       memory: "1059M"
      #   osd:
      #     requests:
      #       cpu: "442m"
      #       memory: "2678M"
      #     limits:
      #       memory: "5944M"
      #   mgr-sidecar:
      #     requests:
      #       cpu: "49m"
      #       memory: "94M"
      #     limits:
      #       memory: "208M"
      #   crashcollector:
      #     requests:
      #       cpu: "15m"
      #       memory: "64M"
      #     limits:
      #       memory: "64M"
      #   logcollector:
      #     requests:
      #       cpu: "100m"
      #       memory: "100M"
      #     limits:
      #       memory: "1G"
      #   cleanup:
      #     requests:
      #       cpu: "250m"
      #       memory: "100M"
      #     limits:
      #       memory: "1G"
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-ceph-blockpool
      isDefault: false
      deletionPolicy: Delete
      annotations:
        k10.kasten.io/is-snapshot-class: "true"

    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              requests:
                cpu: "35m"
                memory: "64M"
              limits:
                memory: "144M"
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 2Gi
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
