---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ceph-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ceph-secret-admin
    creationPolicy: Owner
  data:
    - secretKey: ceph-secret-admin
      remoteRef:
        key: ceph-admin
        property: key
