---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  interval: 30m
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.4
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  values:
    crds:
      enabled: true

    csi:
      provisioner:
        image: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
      cephFSKernelMountOptions: ms_mode=prefer-crc
      csiAddons:
        enabled: false

      enableLiveness: true
      serviceMonitor:
        enabled: true

      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"      

    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}