---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-system
resources:
  - ./namespace.yaml
  - ./minio/ks.yaml
components:
  - ../../components/flux/globals
  - ../../components/flux/alerts