---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-ai-secret
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_API_TOKEN: "{{ .paperless_ai_api_token }}"
        CUSTOM_API_KEY: "{{ .paperless_ai_custom_api_key }}"
  dataFrom:
    - extract:
        key: paperless-ai
      rewrite:
        - regexp:
            source: "(.*)"
            target: "paperless_ai_$1"