# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/home-automation/home-assistant/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: system

  # components:
  #   - ../../../../components/volsync
  # postBuild:
  #   substitute:
  #     APP: *appname
  #     APP_UID: "65534"
  #     APP_GID: "65533"
  #     VOLSYNC_CLAIM: home-assistant-config
  #     VOLSYNC_CAPACITY: 8Gi


