---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          custom:
            matchFeatures:
              - feature: usb.device
                matchExpressions:
                  class: { op: In, value: ["ff"] } #zigbee
                  vendor: { op: In, value: ["10c4"] } #zigbee
                  device: { op: In, value: ["ea60"] } #zigbee
            #   - feature: pci.device
            #     matchExpressions:
            #       vendor: { op: In, value: ["ff","10c4", "ea60"] } #zigbee

            # - name: "zigbee"
            #   matchOn:
            #     - usbId:
            #         class: ["ff"]
            #         vendor: ["10c4"]
            #         device: ["ea60"]
            # - name: intel-gpu
            #   matchOn:
            #     - pciId:
            #         class: ["0300"]
            #         vendor: ["8086"]

