---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  uninstall:
    keepHistory: false
  values:
    master:
      resources:
        requests:
          cpu: 21m
          memory: 51Mi
        limits:
          memory: 51Mi

    worker:
      resources:
        requests:
          cpu: 5m
          memory: 48Mi
        limits:
          memory: 48Mi


