---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
spec:
  interval: 30m
  chart:
    spec:
      chart: akri
      version: 0.13.8
      sourceRef:
        kind: HelmRepository
        name: akri
        namespace: flux-system
      interval: 30m
  values:
    kubernetesDistro: k8s # Specify Kubernetes distro here: k3s|microk8s|k8s
    udev:
      discovery:
       enabled: true