---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./prometheus-community.yaml
  - ./weave-gitops.yaml
  - ./kyverno.yaml
  - ./piraeus.yaml
  - ./democratic-csi.yaml
  - ./truecharts.yaml
  - ./node-feature-discovery.yaml
  - ./rook-ceph.yaml
  - ./intel.yaml
  - ./backube.yaml
  - ./kasten.yaml
