apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-postgres
    namespace: security
stringData:
    #ENC[AES256_GCM,data:6+t7EmXBYhlKlHCKAK/jakRRwy+Ypw4W1xhZNAEIoL5566+bLzINk9POfCvduJSRkDrd,iv:w7Lw1D6I0ij10YU18vmKx87lBi2P4cubzGjCvznIMZM=,tag:MeEHeqiZteJnRXT+LMGsug==,type:comment]
    POSTGRES_URL: ENC[AES256_GCM,data:mzL8F0AlTQwdkLvdIyssg3y+Wc+EZYFU+8RvKi0FkF5k+2m6BEVebPJfQ65sHC5hTQQpDVp6icHKxbnsU8XvAoGBSwdZVURwZD5KIn0D1dg=,iv:7OX+CUx6AiRmwnIiwDqpHcYVmVyAVNuu1996pH8vSCc=,tag:emneBwKvGV8AG0w9VGLbLA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:sNqTLJtOpE1+ui4n+wjegVTQW75C4Rd7,iv:06uBucsLnsjtEWleZIX1XCHcmoeqv5wXDwOFzBK8+ds=,tag:pnV/I1Doxk0aHAFjN2Qkig==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:4KxfiBfP+OSPYks=,iv:Yu5DZvvASFVVVd/YHvalf1Y48HPCpYWP1oKHZFx39Fo=,tag:qBOpoHEhoqJjcBxjoqbHkA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3Gt1/zyMd7EyJb4=,iv:M6uKNDEyenhJJIi9WIitzHdHypStuWi0f50bAqPoM6g=,tag:NuC1A9x/0HOIpiXrTHS64g==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:2NVlk3feb2OEwVPIg5XUUGNt,iv:Te6RSOcJiQT5DHGLje6xH/WKEraBZywdA53gn9BRDuY=,tag:QlZZvOrcuHPKi4UMDnIDfQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNm42c3JadmRIMk9rdE84
            NGV1dTcvZHBxZ2NFTmFJL2xkUXJ1b1BCL0dJCk9vQXZhWXB4alE4a1FId2RBaUdZ
            U0FNTnpZclo2Sy9CRlE5VnpxbkpIN0EKLS0tIG80QnVKNUJIZGQ2NkZWTzFXSHlV
            VHZaaG5XNTN1RHVLdFd0cFJMMzMwYk0KJZDwm8j3D6jRmJYGU70FQcLWCoB0BS4u
            ehMbTnBE+CKCE4bdMj9zfmD2vVABoboXVGRgrNvz4/qZ3LfTN9ax/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-06T20:03:21Z"
    mac: ENC[AES256_GCM,data:q9FpDP0QtgqCsztfMqcwNUQnKNjQTawXRzeYxqTrzxE47F7SQJgqaz91wr+uoXTL3QzDcQKTzQg/89Itk8f3uxSlOzUkv9jBoWekv9IskgO5J1+tK+1Jcd5bnAuKj0ZPXpzMyJi/S7wDC1rR6cEeQr2gBjb6Yl5Trx4mNWDKcQI=,iv:U/VLtZzMi5mzClBhi4Dbqw15BPSbyQv+JXG982nJCsA=,tag:ganFPe/UpjwS6JVy6Y00GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
