---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      serviceMonitor:
        create: true

    # https://artifacthub.io/packages/helm/piraeus-charts/snapshot-controller
    # volumeSnapshotClasses:
    #   - name: csi-ceph-blockpool
    #     driver: rook-ceph.rbd.csi.ceph.com
    #     annotations:
    #       snapshot.storage.kubernetes.io/is-default-class: "true"
    #       k10.kasten.io/is-snapshot-class: "true"
    #     parameters:
    #       clusterID: rook-ceph
    #       csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
    #       csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph
    #     deletionPolicy: Delete
