---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app.kubernetes.io/instance: mosquitto
configMapGenerator:
  - name: mosquitto-configmap
    files:
      - config/mosquitto.conf
generatorOptions:
  disableNameSuffixHash: true
