---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mosquitto-data"
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "mosquitto-bootstrap"
  resources:
    requests:
      storage: 512Mi
  storageClassName: ceph-block
