# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home-automation
stringData:
    mosquitto_pwd: ENC[AES256_GCM,data:AWxyjg8niVhPY5CHqpzN0Cyd84+0aEa3kLx0Cf2cK/Ol9etZQ2CERE4/Pjp0oq5fTS2WEw24phYpxmwr44/9LsIUT+PqyJntqiFJueP7LcsS4ammHM6YKveeSUYa+JZA9+1In4PuOFnTNdbd+dnPVg==,iv:ijm9QKey+BBMF+6+YsYJHNotIB6yHzktC1sYATjdQ5Y=,tag:VCfF4FMlvrrrMjX3heQTUw==,type:str]
# {{ .mosquitto_username }}:{{ .mosquitto_password }}
# {{ .mosquitto_zigbee2mqtt_username }}:{{ .mosquitto_zigbee2mqtt_password }}
# {{ .mosquitto_frigate_username }}:{{ .mosquitto_frigate_password }}
# {{ .mosquitto_esp_username }}:{{ .mosquitto_esp_password }}
# {{ .mosquitto_amcrest2mqtt_username }}:{{ .mosquitto_amcrest2mqtt_password }}
# {{ .mosquitto_home_assistant_username }}:{{ .mosquitto_home_assistant_password }}
# {{ .mosquitto_octoprint_username }}:{{ .mosquitto_octoprint_password }}
# PAPERLESS_SECRET_KEY: ZdBxR8MKjKg9sR9GJFDnnvjhpZgcGKh5GfSexufjZQKEfNdosV
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVmhtSDdvdy9TRWhrWnFD
            TWVpZzlvS0dLeVR4aDV5dmRLZjViQkYxTVhRCm5WWkE3eW9uZEwzV3V6amFFd1FT
            RHkxZkg5ODdVUDBlenl5TDU0TVNXQ0UKLS0tIERiMWt4VkU3Q2RFbVhEdFVNYVlJ
            N3Qxb1ZZdHExYWw3UGxVZnhTOWtkWEUKKcTFkf6BggkaKsyoZxPtVwOmHxs9hVrt
            4COzgfULpqlZQaaFAN4PgxJhSLtUFsZDOEBa2z8LLNoWd/jkpziYbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:16:34Z"
    mac: ENC[AES256_GCM,data:YThwPzmNz4QMj7bTiTMWN2FXI6jcWVXguIO//G5DNyPaoNwHtnzPjJcZ2t7bqWQquxrCXsUv5WddkzRkTDe6oGCo1ZetFhgm96PBa/zAIVyz7CvrXlmB6/MOUyjamYLTyYBdWaK2J04XehBeldce0dJYfjGk3mqtn88rQL8geBg=,iv:wurpGSvT0muKM3XhU8sGQE7VU5Gt9JbJffJkwabfC+Y=,tag:WRRO+JPASlW8O7E8qKC6gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:twZZowYv8ujJBotwM6j3lE7PGlNxsU/eumwh2mZokuwJkEaA5Ev46ZaIRha/MjRarinwZsIz7da0z7fit6f4k1QAtEhnlRLIpl8DGsXR2bL/,iv:avMSb4X/W6qU13CMlOxyuedTdqplkTzLUV9lhtRm/zw=,tag:y5FuMNUtMMIni4snNEz7sg==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YXdBxZ7ukezokzAdIsOME/aUpydacie7eEPQPceDcc7wO3KIEJf0ZEHEwO31sp1G7PbV,iv:K+qROnWquaqpeOdNML8TNaay4d0TIOHSr3/7preCgAY=,tag:GYQBDlAvMsvT4xoNODSf7g==,type:str]
    #ENC[AES256_GCM,data:NwlwYP2gMR2BP394ssfGV8McyIqQlR2Zh+CsN0CikGdmi1mbVG3iclrSIdFNfcSvtft2H7wHACAjXzlh3dwd0SNHU4L976AJF6Kan0scDVXnJn+4U3tHaX0KFJphno3yfhlMEg==,iv:BIRo1MB3LhX9FfLTsRWr4Yv1gptEQAZmHwGjcgvLyOQ=,tag:tZuwcv8Crfbi4nkYCZP3wg==,type:comment]
    #ENC[AES256_GCM,data:EvDOtm2Sf5lPeney3jIQo6NHHc+nneR+0odNJCRgjkj2xhSp1EJtCiGgMi4L51ESD1M4eJdYTkran1CP57ad0SHPP97okf/hiyiATDsuf0iltM1k3TxTDIZ4tHYPeTA=,iv:+rNfO5NPXAGEv6XxMOQMB7GmE4DJaEeER0GQ6y19UFU=,tag:jwgjESxx4ndO6zVgFPW3Nw==,type:comment]
    #ENC[AES256_GCM,data:G+OE8q7X8vBmPxcavaeivOsCBk+8+McPlLQ4DbVExbIyyPrGD+TQeKDTtIUO8grvhegOEIESxJG9N3mhZHMDhvgUivKsCjcWdYb0yQ8UJVe+hNYhYg==,iv:GM4JqxM+46uR8lGZ6JhmKNROuwTQrOo4NHsvz9c/bQI=,tag:4J68g0WlToMqci4se0wgqA==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:RQMD0pEAoqSyyqMNDP4FPRjj,iv:WMNh8fF66z4NIOnbIDVr7KLrWTpXngXILsqgOAlZKL8=,tag:UQtFZr8CsmhFX/4BVBKdiA==,type:str]
    #ENC[AES256_GCM,data:iQe8pWFyYQjbMtjpRu8yuQT9bS22rf7i7/bUGfxPTUPkHw==,iv:te+c5Gl+xnaYb0aOyA4KDjE+ZRbaIKQEpqVjGrlEj/Q=,tag:JpryNpWS7DuUB+e5S8UorQ==,type:comment]
    #ENC[AES256_GCM,data:CPn00eqfRw6OEC8jWghJsAgyVcdpYQWJk4fS3OMSjllW5XwOJCboTQb5ezDladjE0mR76Ujm8DJwrH6yxapodXEXJN7FBw==,iv:cBsC71ppzDM8xQz4b3KXfNLBVd0zQTW39v1p/v/J8F4=,tag:utrawd0i1wATkNfE1S4FBg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OOHCjFt4dA==,iv:1IW3NErzHNC2d9sGefNE4ZHGY2wSdgsy/B8oHsfraU0=,tag:em6XkpW/QoAfQ2xOg1xwog==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F+II3QqTu6bHduuWADtntv0ZRQ==,iv:ipsYEV0eh3Ml8ws27jLwzr5K944tkViJBTAQubV41Rc=,tag:qJ9BRmHYzqdY6QoU4AXrQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVmhtSDdvdy9TRWhrWnFD
            TWVpZzlvS0dLeVR4aDV5dmRLZjViQkYxTVhRCm5WWkE3eW9uZEwzV3V6amFFd1FT
            RHkxZkg5ODdVUDBlenl5TDU0TVNXQ0UKLS0tIERiMWt4VkU3Q2RFbVhEdFVNYVlJ
            N3Qxb1ZZdHExYWw3UGxVZnhTOWtkWEUKKcTFkf6BggkaKsyoZxPtVwOmHxs9hVrt
            4COzgfULpqlZQaaFAN4PgxJhSLtUFsZDOEBa2z8LLNoWd/jkpziYbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:16:34Z"
    mac: ENC[AES256_GCM,data:YThwPzmNz4QMj7bTiTMWN2FXI6jcWVXguIO//G5DNyPaoNwHtnzPjJcZ2t7bqWQquxrCXsUv5WddkzRkTDe6oGCo1ZetFhgm96PBa/zAIVyz7CvrXlmB6/MOUyjamYLTyYBdWaK2J04XehBeldce0dJYfjGk3mqtn88rQL8geBg=,iv:wurpGSvT0muKM3XhU8sGQE7VU5Gt9JbJffJkwabfC+Y=,tag:WRRO+JPASlW8O7E8qKC6gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
