# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: home-automation
stringData:
    mosquitto_pwd: |
        admin:admin@123
        admin:admin@123
        admin:admin@123
        admin:admin@123
        admin:admin@123
        admin:admin@123
        admin:admin@123
# {{ .mosquitto_username }}:{{ .mosquitto_password }}
# {{ .mosquitto_zigbee2mqtt_username }}:{{ .mosquitto_zigbee2mqtt_password }}
# {{ .mosquitto_frigate_username }}:{{ .mosquitto_frigate_password }}
# {{ .mosquitto_esp_username }}:{{ .mosquitto_esp_password }}
# {{ .mosquitto_amcrest2mqtt_username }}:{{ .mosquitto_amcrest2mqtt_password }}
# {{ .mosquitto_home_assistant_username }}:{{ .mosquitto_home_assistant_password }}
# {{ .mosquitto_octoprint_username }}:{{ .mosquitto_octoprint_password }}
# PAPERLESS_SECRET_KEY: ZdBxR8MKjKg9sR9GJFDnnvjhpZgcGKh5GfSexufjZQKEfNdosV
---
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    # The repository url with pvc-b-backup as the subpath under the restic-repo bucket
    RESTIC_REPOSITORY: s3:http://minio.default:9000/volsync/main/mosquitto
    # The repository encryption key - using a different key from pvc-a.  This will not prevent overwrites
    # or deletes of the data for others who have access to the bucket, but will prevent reads/writes
    # to the restic data in the pvc-b-backup folder for those without this encryption key.
    RESTIC_PASSWORD: Us8PVjnKjok3NBcx99
    # ENV vars specific to the back end
    # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
    AWS_ACCESS_KEY_ID: volsync
    AWS_SECRET_ACCESS_KEY: wdf@DAU5xcp@ukb7dkz
