---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  sourcePVC: data-mosquitto-0
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: mosquitto-restic-secret
    retain:
      daily: 14
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-hostpath
