---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mosquitto
spec:
  sourcePVC: mosquitto-data
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot 
    repository: mosquitto-restic-secret
    cacheStorageClassName: "openebs-hostpath"
    cacheAccessModes: [ReadWriteOnce]
    cacheCapacity: "1Gi"
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "mosquitto-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: mosquitto-restic-secret
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 8Gi
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 1003
      runAsGroup: 1003
      fsGroup: 568
    accessModes:
      - ReadWriteOnce
    capacity: 512Mi

