---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-unbound
  namespace: network
spec:
  chart:
    spec:
      chart: external-dns
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-unbound
  interval: 30m
  values:
    fullnameOverride: externaldns-unbound
    logLevel: &logLevel debug
    domainFilters:
      - f-wi.com
    podAnnotations:
      secret.reloader.stakater.com/reload: unbound-certificates
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/guillomep/external-dns-unbound-webhook
          tag: v0.1.3
        env:
        - name: LOG_LEVEL
          value: *logLevel
        - name: UNBOUND_HOST
          value: tcp://10.11.0.1:953
        - name: UNBOUND_CA_PEM_PATH
          value: /usr/local/etc/unbound/ca.pem
        - name: UNBOUND_CERT_PEM_PATH
          value: /usr/local/etc/unbound/client.pem
        - name: UNBOUND_KEY_PEM_PATH
          value: /usr/local/etc/unbound/client.key
        livenessProbe:
          httpGet:
            path: /health
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        extraVolumeMounts:
        - name: unbound-certificates
          mountPath: /usr/local/etc/unbound/
    extraVolumes:
    - name: unbound-certificates
      secret:
        secretName: unbound-certificates

    resources:
      requests:
        cpu: 16m
        memory: 90M
      limits:
        memory: 90M
    serviceMonitor:
      enabled: true
    sources:
      - crd
      - gateway-httproute
      - service
    extraArgs:
      - --gateway-name=envoy-internal
    triggerLoopOnEvent: true
    txtOwnerId: main
    txtPrefix: "k8s."
