---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      version: 7.3.12
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 30m
  timeout: 20m

  values:
    replicas: 1

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: node-exporter
            disableDeletion: false
            editable: true
            folder: "node-exporter"
            options:
              path: /var/lib/grafana/dashboards/node-exporter
            orgId: 1
            type: file
          - name: omada-exporter
            disableDeletion: false
            editable: true
            folder: "omada-exporter"
            options:
              path: /var/lib/grafana/dashboards/omada-exporter
            orgId: 1
            type: file

    dashboards:
      default:
        speedtest-exporter-hub:
          gnetId: 13665
          revision: 4
          datasource:
            - name: "DS_PROMETHEUS"
              value: Prometheus

      node-exporter:
        # Ref: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
        node-exporter:
          gnetId: 1860
          revision: 29
          datasource: Prometheus

      omada-exporter:
        # Ref: https://grafana.com/grafana/dashboards/16343
        omada-exporter:
          gnetId: 16343
          revision: 2
          datasource:
            - name: "DS_PROMETHEUS"
              value: Prometheus

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - access: proxy
            isDefault: true
            name: Prometheus
            type: prometheus
            url: http://thanos-query.monitoring:9090
          # - access: proxy
          #   name: Loki
          #   type: loki
          #   url: http://loki-gateway.monitoring.svc.cluster.local:80
          # - name: Alertmanager
          #   type: alertmanager
          #   access: proxy
          #   url: http://alertmanager.monitoring.svc.cluster.local:9093
          #   jsonData:
          #     implementation: prometheus
        deleteDatasources:
          - name: Loki
            orgId: 1
          - name: Alertmanager
            orgId: 1

    deploymentStrategy:
      type: Recreate

      admin:
      existingSecret: grafana-admin-secret


    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false

      dashboards:
        default_home_dashboard_path: /tmp/dashboards/home.json
      date_formats:
        use_browser_locale: true
      explore:
        enabled: true
      grafana_net:
        url: https://grafana.net
      log:
        mode: console
      news:
        news_feed_enabled: false
      panels:
        disable_sanitize_html: true
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      security:
        allow_embedding: true
        cookie_samesite: grafana
      server:
        root_url: "https://grafana.${SECRET_DOMAIN}"

    imageRenderer:
      enabled: true

    persistence:
      enabled: false

    plugins:
      - natel-discrete-panel
      - pr0ps-trackmap-panel
      - grafana-piechart-panel
      - vonage-status-panel
      - grafana-worldmap-panel
      - grafana-clock-panel


    serviceMonitor:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/icon: simple-icons:grafana
      hosts:
        - &host "grafana.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host

    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
        label: grafana_dashboard
        folderAnnotation: grafana_folder
        searchNamespace: ALL
        provider:
          disableDelete: true
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        labelValue: ""
        searchNamespace: ALL
      logLevel: INFO
