apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:GXmhLsvxjtr1,iv:ZNM1GjWc2TZD/wBkqHAy7S5Xpyn6pjrKuedv1mYlN6g=,tag:6midReQjk56e5xEREpHteA==,type:str]
    admin-user: ENC[AES256_GCM,data:4Qiy0WY=,iv:ve/Z/m7qaJD69dC/JLFlr8Q9hxSzvPR6AvLocUwAbIc=,tag:TVSsMscnuDFzk8xg4affUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEV4NWxWZFU3ZTRIaWtn
            VUc5MWErazVJelFOT2RVK0dHTXRtM3g0NEdVClgrYUV6TEc0UEVqT3NEb2Qwck5y
            UUxSZVBoc01sRXlhN3pxazRrK0V1amsKLS0tIExWOW90cW9aVkNDenExdGxZajhE
            MkpoQSthUE9GZCtMR0t3aEVQR3Q4Wk0KIY/WmlMSARLbdz19puvvTsgNH9LtW4pm
            Xaeiclj4lvBgNmWes/9asX/JWS1J0zNhPHr/rI5VuJOYVDDRLAKATQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-27T05:21:36Z"
    mac: ENC[AES256_GCM,data:Ls9+ak0fHJ1X0NfnYRTEJofirqUmNRo2uOZzXsrXyBv+9bH/dF+IG7DlxIoW2/FiqiN+NoOeCu24vbZL3qxLRLU7DINTkyD6LumzxrRLSu6ZpfHWZfDJCq5jteOJSlx/+jno5mbF/1Ukdal9W0ZOofuUp4DpKhnrGejtW8EpxsQ=,iv:9+p6ritcBQvdqHNtQvFEENn7AEuTI7pBZoxp7jExRcY=,tag:ge6g98ErG2jJWcOMW+zNEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
