apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:Y4A=,iv:cwvHEJrk/QTqQ2cZZHGKPGNLdRRGCuN3GFFtikgx3g0=,tag:w+cG+M/uDnpqzkNA0NgX7g==,type:str]
    password: ENC[AES256_GCM,data:PTpjPsK2Ruw5fVafjzsm+gbU,iv:fDeyEg1QZ/kJUYBym6JlFVvW5Kg0Lz47rBV/ub0rXyM=,tag:6ejnogStiGGGgIEPBubLkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T07:02:40Z"
    mac: ENC[AES256_GCM,data:TuoXEwTIL7PDn9gdF/cW9ZL/xb9jEXOc7BN+ck10cVpnn9Lyww908lcf+YRftwEdn0rIsU1b3P/AFj88xtB0T3SB8u6SgjeW2HZS0Ks9YDPRyb7vZEWB9bi0uV+EtvyfKAoJKgKhbGJk8wWXdUDKDAsf5TTeo1lqyP4OOn1R7hk=,iv:nKe773lu+hwoyz1M8DWYwa57J59ve40um5DiN9wfOSY=,tag:PVOPliKOK7dO8YsGlt5wZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:tHeq3bYwRZk=,iv:lnfICXKZyBLeArIIZGYaT3AIj7GWZAPeSi7Muw8xUhU=,tag:hs7tJk9wh2pvXgAjDkOeeA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:XNhGnoHn84iOqjrNpDglvWvVdO9dpZn1+d1hRGU61mKKGiG/DpM8Hg==,iv:88KdOBxdwxuOUb4pXKSbIelNcuGorT6KYCaE8FpVNCE=,tag:smcxcmzUdKDg7Prm+JThhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T07:02:40Z"
    mac: ENC[AES256_GCM,data:TuoXEwTIL7PDn9gdF/cW9ZL/xb9jEXOc7BN+ck10cVpnn9Lyww908lcf+YRftwEdn0rIsU1b3P/AFj88xtB0T3SB8u6SgjeW2HZS0Ks9YDPRyb7vZEWB9bi0uV+EtvyfKAoJKgKhbGJk8wWXdUDKDAsf5TTeo1lqyP4OOn1R7hk=,iv:nKe773lu+hwoyz1M8DWYwa57J59ve40um5DiN9wfOSY=,tag:PVOPliKOK7dO8YsGlt5wZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
