---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: system
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
    - name: nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    volumeSnapshotClasses:
    - name: nfs
      parameters:
        detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: https
          host: 192.168.10.10
          port: 443
          apiKey: 2-CgYsQ1QcqN4D7D76jkvi1rQRU1GXsnh62xkhnCscnXzka8xcD4jDCXy8TWgJFljS
          #   existingSecret: truenas-csi-secret
          existingSecret: truenas-csi-secret
          allowInsecure: true
          apiVersion: 2
        zfs:
          datasetParentName: Volume1/k8s/nfs/v
          detachedSnapshotsDatasetParentName: Volume1/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 192.168.10.10
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
