apiVersion: v1
kind: Secret
metadata:
    name: truenas-csi-secret
    namespace: system
stringData:
    apikey: ENC[AES256_GCM,data:qzRZkdE9/VbwSRsbS2xZ8MB+dSkkLk1r7h1emCQ+C3lam/WNCWE9kW9Q8RDWVw7RRfilRoqJDVFcHTGlXWdbOx0I,iv:LqDM64yEfgLzLUqQGf1qimSEJUZ36F5jwPwUwPrWgSk=,tag:DXUx9LsuiciCNQPsYzazEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTWttL3ZPZzgzbEJVR2FS
            eW9PSW1BRW1zd0pvZ1R3Z1c0eGw0Q0RLOUdvCjdrOW0yakMxYlRDcEpqK0xRWG9X
            U0xOODl6WC9QZVVIdHM3dDd1V2RsYjAKLS0tIFdOaURIMkIxSS9pMmExbjJoVGcv
            Z2c2dkRPdFhEZTZFeGhnUHdvSVF5UVEK9Ha/28rk6m/Nc8szBC4hY4UtNhhrF0lx
            5/I4SwZvhQxgl8eCMi8FGbaLWzPzvscf76xYjYlmLxbmk45hfExDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-06T07:24:33Z"
    mac: ENC[AES256_GCM,data:289f1n39annvhDQUhf/HzqsCYzBpZ2KbeL0rMG0Xfi9mulohlaf6tB6/yuQ9kdIu7Smlbo2vqjhGFnLDLJdYyT//5wQR1lq2tXLOuHNJgb9yenBDflDrgUxQ/uPTr0h24qPKMYWqDK9GnROg/NpJIsM9HI5KyjI3pO1RkeBOGmg=,iv:IvHre6TNr4P3cK8lbDnx3vU/l2syirjR+v/CkZw/UjI=,tag:TxnifaD1YwDUz2VE28jplw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
