---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: *app
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-10-29T16-01-48Z
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2024-10-29T16-01-48Z
    mode: standalone

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      enabled: true  

      ## A manually managed Persistent Volume and Claim
      ## Requires persistence.enabled: true
      ## If defined, PVC must be created manually before volume will be bound
      existingClaim: "minio-nfs"
    
    existingSecret: minio-secret

    networkPolicy:
      enabled: true
      flavor: cilium
