# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:qPQZ0BY=,iv:YhrXTkCIEplNhqpg9cwPRGdVGnJt4GDMdTKD5hnqTe4=,tag:LvK2erlv5jXlU4ce4r2kFw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:DMTdvBxf0qOy,iv:PWn1pZP6wZa7fsqNaXcxfCUcdUvkQ5sKnO/mVkrZfS8=,tag:9dhiM1zI6rsAhJm8mQ1d8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T19:18:45Z"
    mac: ENC[AES256_GCM,data:4Z8KwGP7bMKSGBV3Ic+FUbQcS4ErUKluFby+qWaje+5nJDtKq2f0ErJkdp+GOwSAwsivfnrYeW4EkuzgiLks0dd0UWB1xT5DiIUU1vO0wkU7oRmjpNT5Qoq8tGd63/ZXo6stl1kpP8dHFNTfSvJgevSEqLccGCdL0nOV2lJQpQM=,iv:JoXrHdlkolbckXcSOs2gtnOHeXLaSlU9qzzY8HIC63Y=,tag:/CFRpygeBzhGwOS59o/1GA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
