---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  path: "./kubernetes/apps/system/intel-device-plugins/operator"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: node-feature-discovery
      namespace: system
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
spec:
  path: "./kubernetes/apps/system/intel-device-plugins/gpu"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: intel-device-plugins-operator
      namespace: system
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
