---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      serviceMonitor:
        enabled: true

        dashboards:
          enabled: true
          label: grafana_dashboard
          namespace: monitoring
          labelValue: "1"
          annotations: {}

        relay:
          prometheus:
            serviceMonitor:
              enabled: true

        ui:
          ingress:
            enabled: true
            className: "internal"
            hosts:
              - &host "hubble-home-cluster.${SECRET_DOMAIN}"
            tls:
              - hosts:
                  - *host

      prometheus:
        serviceMonitor:
          enabled: true

      operator:
        prometheus:
          serviceMonitor:
            enabled: true