---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cluster:
      name: home-cluster
      id: 1

    cni:
      exclusive: false

    bgp:
      enabled: false
      announce:
        loadbalancerIP: true
        podCIDR: false

    bgpControlPlane:
      enabled: true

    k8sServiceHost: ${CUSTER_API_DOMAIN}
    k8sServicePort: 6443

    rollOutCiliumPods: true
    localRedirectPolicy: true

    kubeProxyReplacement: strict
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

    loadBalancer:
      algorithm: maglev
      mode: dsr

    bandwidthManager:
      enabled: true
      bbr: true
    bpf:
      masquerade: true
      tproxy: true

    l7Proxy: true

    enableCnpStatusUpdates: true
    endpointStatus:
      enabled: true
      status: "policy"

    ipam:
      mode: "kubernetes"

    ingressController:
      enabled: false
      loadbalancerMode: shared

    operator:
      rollOutPods: true

    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR:  ${CLUSTER_CIDR}
    tunnel: "disabled"
    containerRuntime:
      integration: containerd

    hubble:
      enabled: true
      serviceMonitor:
        enabled: false

      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http

      relay:
        enabled: true
        rollOutPods: true

      ui:
        enabled: true
        ingress:
          enabled: false
        rollOutPods: true

    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
