---
cluster:
  name: "cluster01"
  id: "1"
rollOutCiliumPods: true
localRedirectPolicy: true
kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
ipv4NativeRoutingCIDR: 10.244.0.0/16
k8sServiceHost: 192.168.40.20
k8sServicePort: 6443
loadBalancer:
  algorithm: "maglev"
  mode: "dsr"
tunnel: "disabled"
autoDirectNodeRoutes: true
endpointRoutes:
  enabled: true
ipam:
  mode: "kubernetes"
operator:
  rollOutPods: true
containerRuntime:
  integration: containerd
securityContext:
  privileged: true
hubble:
  enabled: false
bgp:
  enabled: false
  announce:
    loadbalancerIP: true