---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multiprotocol
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      multiprotocol:
        annotations:
          reloader.stakater.com/auto: "true"
        
        pod:  
          hostNetwork: true
                    # -- Affinity constraint rules to place the Pod on a specific node.
          # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: google.feature.node.kubernetes.io/multiprotocol-usb
                    operator: In
                    values:
                    - "true"

        containers:
          app:
            image:
              repository: homeassistant/amd64-addon-silabs-multiprotocol
              tag: 2.4.5
            env:
              # # -- Port where ser2sock listens
              # LISTENER_PORT: 10000
              # # -- Path to the serial device
              DEVICE: "/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231120161348-if00" # "/dev/ttyACM0"
              # # -- Serial device baud rate
              BAUDRATE: "460800"
              OTBR_LOG_LEVEL: "debug"
              OTBR_ENABLE: "true"
              OTB_FIREWALL: "true"
              OTBR_REST_LISTEN_PORT: "8081"
              OTBR_WEB_PORT: "8086"

              # ZIGBEED environment variables
              EZSP_LISTEN_PORT: "20108"

              BACKBONE_IF: "eth0"
              FLOW_CONTROL: "false"
              NETWORK_DEVICE: ""
              AUTOFLASH_FIRMWARE: "false"
              FIRMWARE: ""
            
            securityContext:
              # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
              privileged:  true
              capabilities:
                add:
                - IPC_LOCK
                - NET_ADMIN

  

    service:
      app:
        controller: multiprotocol
        ports:
          # http:
          #   enabled: false
          server:
            enabled: true
            protocol: TCP
            port: 10000

    # ingress:
    #   app:
    #     enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml
      usb:
        enabled: true
        type: hostPath
        hostPath: /serial # /dev/ttyACM0