---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multiprotocol
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: homeassistant/amd64-addon-silabs-multiprotocol
      tag: 2.4.3
    env:
      # # -- Port where ser2sock listens
      # LISTENER_PORT: 10000
      # # -- Path to the serial device
      DEVICE: /dev/ttyUSB0
      # # -- Serial device baud rate
      BAUDRATE: 460800
      OTBR_LOG_LEVEL: "debug"
      OTBR_ENABLE: 1
      OTB_FIREWALL: 1
      OTBR_REST_LISTEN_PORT: "8081"
      OTBR_WEB_PORT: "8086"
      EZSP_LISTEN_PORT: "20108"
      BACKBONE_IF: "eth0"
      FLOW_CONTROL: true
      NETWORK_DEVICES: 0
      NETWORK_DEVICE: ""
      AUTOFLASH_FIRMWARE: 0
      FIRMWARE: ""
    service:
      main:
        ports:
          http:
            enabled: false
          server:
            enabled: true
            protocol: TCP
            port: 10000

    ingress:
      main:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyUSB0

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged:  true

    # -- Affinity constraint rules to place the Pod on a specific node.
    # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/usb-ff_10c4_ea60.present
              operator: In
              values:
              - "true"
