---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: faster-whisper-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      faster-whisper-server:
        annotations:
          reloader.stakater.com/auto: "true"
        
        pod:
          labels:
            ingress.home.arpa/nginx-internal: allow
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place

        containers:
          app:
            image:
              repository: fedirz/faster-whisper-server
              tag: 0.0.5-cpu
            args:
              - --model
              - small

            resources:
              limits:
                cpu: 12000m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi

    service:
      app:
        controller: faster-whisper-server
        ports:
          http:
            port: 8000

    ingress:
      app:
        className: "internal"
        hosts:
          - host: &hostName "faster-whisper-server.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *hostName

    persistence:
      data:
        existingClaim: faster-whisper-server-data
        advancedMounts:
          whisper:
            app:
              - path: /data