---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml

commonLabels:
  app.kubernetes.io/name: faster-whisper-server
  app.kubernetes.io/instance: faster-whisper-server
