---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "zigbee2mqtt-data"
spec:
  accessModes:
    - ReadWriteOnce
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "zigbee2mqtt-bootstrap"
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
