---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Direct
    repository: zigbee2mqtt-restic-secret
    destinationPVC: data-zigbee2mqtt-0
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568

