apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
type: Opaque
stringData:
    mqtt_password: ENC[AES256_GCM,data:98dOVefIed0i,iv:WS6ChD/W1MObV6Bf6Lyq1A2+5nFQNBL5W7zcrGn0YXc=,tag:Lvr8YzCyl7+lRaaAP7IFQw==,type:str]
    mqtt_user: ENC[AES256_GCM,data:hGqqrw4=,iv:iHNvf88WPdL0+FhLP43cWC5sLLTPDf9dSmF+RrUu/Rg=,tag:0MNVJmZovPhJfc196u5RKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T13:40:57Z"
    mac: ENC[AES256_GCM,data:Pba3jC/PARVjYJoz653OYiOO0Hj09zToDEGcj99NrL25Wv5uJwWxvEBKNVccgkplYXbw20Nj9pSs8tSa0+sNnEu6b2OCORdAlN4lyDQHmxuN/SGET6y1nfqf6ZgczKhVPpVOeUVejOJglDrnJFuoB+RGnIQdsPxcYRKhgA7oajk=,iv:KseOkgZ/GAc/w9qoq32ddN52WTLjMEQK+D82GQcxSKE=,tag:P9M6d9BJyEGI7m2Wsxu7Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PWVk8p/tDrTsCATUYTjrvn5jdXRXzTQujeLp1HxDS/VSDd0phnU4vOvB89oJ38+rWAhkJo2+TlUbDM74mIPkufdodIav9a8O1uMkExwLKk/g,iv:Udn4aZ3Qv26hsLN8gwPjIc/WbmZ1OD5d/eBUoxENwRk=,tag:dafG1Er2wXtIeYS8CwFvDw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:80xCGUWeyXZaKBJQmu4cLNKA3CZNPdFfmB8RgeElOaQYkrMT+AJM2TWaWdwPGA==,iv:a1EIGqqdyo/RI1PaHp5C3eWkxpcbXuXtytqzBYldrww=,tag:JCyNn0+9gXW7twwL2NWvNQ==,type:str]
    #ENC[AES256_GCM,data:pQWk7bQSBQhI5vkhFcosRY5Q5unXCyu5qNGj7jf9vxWxzVSZ7KyyVAFntpTo1jLEMDIBwuGgh8cuRE8XEx2Zm0lNpwIdAY3vvLI3hidWoKWRbWUGFL/zIAWgll5QnexoGdKjYg==,iv:Nkyl98g7NkM3+h8jVuNDzg8MgFG2uexPxqwYVLpSo68=,tag:NXdPVnBDDV6I0a4MYlO+qQ==,type:comment]
    #ENC[AES256_GCM,data:E/GX03e+/+dxhUpOl1tySiDOxGDM3aqwMsHrGihEb4J24h6rEBblHSF09+JlJPulsQTprGW8ICGrPPpJVsNfdKm43zQAJ0rptSN0Z6SmD/3XE36sNamsMHZ3fyhsYVs=,iv:IRcbSDuJUGziecVQun0enxEfnkRG8dD7HDv1OqT6sQw=,tag:lYtOtK6DeEoV7fYBcGXiaA==,type:comment]
    #ENC[AES256_GCM,data:90SNvNxizBQdRqYLkkjo7GRGXpF0V+fUHs0Sm3mAwSMBfRYUF9YSv3PbXsaOETSLCD/MdQWxuJcmD+m3JEroDJrWpylYpYcK4zatIGNNjnvKYCXHYA==,iv:rA+CpkpPzrbgbTFoqT04GCWZqjj31zWDvab4zCisR3c=,tag:mlQ575UHRjR7nXZwxjf5lQ==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IUT/nl6RYzsZIovFv3rijNfP,iv:6GShr/TvuX3H23qyYDMF+U2nXg/yGj/zTctWND79lyc=,tag:W15MOzTw4KX2K4yjW/+9vQ==,type:str]
    #ENC[AES256_GCM,data:9NAwkuCY4nUTumxW66bwL2jq0xncj4BnGV0ftscj9MWYJA==,iv:NXUGcUvgMwhf6fbIkfMvfNqe6Ixy+cpLSs+1B7pM/N8=,tag:IE25IZox7aEsUnPmhmning==,type:comment]
    #ENC[AES256_GCM,data:cnQJ8LVStu94O6sIccQCxm/uEZXUVbqyCv9PfYrAjOcI6Ic2x1dfjvCLI1aIlTpiiAYWn9+Tpl+9t2r6Z/z2M97tUrPdEg==,iv:FHT2F5YAlayP8w3nfeQanipyBOX4xSxiIoztLmXDDo0=,tag:Y3dhQXLZao7DlEjsDklsdA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MtdzJwFRJD0alPc=,iv:oMNwU3QpNjTsJ4cRGaUSV8rgUu5+SALJaNSi+T7KfZQ=,tag:Y5qg0RqgjpRVNzYTZhWVoQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z4RfEbNIK+QXbDQ0MVpTFgvLnbOhUDmOr2SzwWQPx+9WO0zTnNC0CA==,iv:2cFmsPQhCdrsEdi+SaavwiIFduFEd/IlkTYYXAqQIuc=,tag:9nBIcwRA/lUKNyTqYUHSxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T13:40:57Z"
    mac: ENC[AES256_GCM,data:Pba3jC/PARVjYJoz653OYiOO0Hj09zToDEGcj99NrL25Wv5uJwWxvEBKNVccgkplYXbw20Nj9pSs8tSa0+sNnEu6b2OCORdAlN4lyDQHmxuN/SGET6y1nfqf6ZgczKhVPpVOeUVejOJglDrnJFuoB+RGnIQdsPxcYRKhgA7oajk=,iv:KseOkgZ/GAc/w9qoq32ddN52WTLjMEQK+D82GQcxSKE=,tag:P9M6d9BJyEGI7m2Wsxu7Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
