apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
type: Opaque
stringData:
    mqtt_password: admin@123
    mqtt_user: admin
---
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    # The repository url with pvc-b-backup as the subpath under the restic-repo bucket
    RESTIC_REPOSITORY: s3:http://minio.minio-system.svc:9000/volsync/main/zigbee2mqtt
    # The repository encryption key - using a different key from pvc-a.  This will not prevent overwrites
    # or deletes of the data for others who have access to the bucket, but will prevent reads/writes
    # to the restic data in the pvc-b-backup folder for those without this encryption key.
    RESTIC_PASSWORD: Us8PVjnKjok3NBcx99
    # ENV vars specific to the back end
    # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
    AWS_ACCESS_KEY_ID: volsync
    AWS_SECRET_ACCESS_KEY: wdf@DAU5xcp@ukb7dkz
