apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
type: Opaque
stringData:
    mqtt_password: ENC[AES256_GCM,data:jJTrfEpVFGri,iv:oVUyxtbnd8C6U1UVbPOBLqCP8VdGIh70CyIydSBvet0=,tag:o+zk7ZTyx+BCOllKIj0kPQ==,type:str]
    mqtt_user: ENC[AES256_GCM,data:HtzYdIM=,iv:sGvObU5RT2+9H7zE1EWblGnsKys2dj0It5EIDgrYouU=,tag:hKInIvOlsV67lSfCkur8tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dE0wazlacmZxWURHWUFm
            WnloYWRXeStaTkhYZUVEYU5uTFc3cXA3bkQ0ClQ5aHRnZ2tSblYvc2N6Zi9tRGVG
            QkRFZ0VGK1VwVGZLSEJ0V2JvamVzb1kKLS0tIERFdmNFY2NieldvTkZSZlhHa2kv
            VDVQZUZmYUMvMmxTdklpR1B5R3VibHMKTu+vP+c4sZnrr+4ZkCDCfrA1M2qaiwOu
            I8ck8w0mRKn26AXIHpqGnVPprCCYKxO4ZbjFaUNNYDrV4/ifrjDH9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:06:38Z"
    mac: ENC[AES256_GCM,data:HDWen//KGQVXGO8Je7zcUx0OUF1Izg3dsTVnfzjj7W/EbWxIhf0nJ2l5Daxtbg0ulUgu4xkaJxT7mDgGczcXKihXnja2qtvQB3Fxzaah+Gm6p/0leJcD3JoyVad/JIYVoAb1IM9tChl59YKkmSWDF0PKUbajdlZWAVh0N/djfbY=,iv:+UMNFW774Mtr3cyO2kurOlyDraIhuwiPR90mXRJx8kc=,tag:tBFdQ3cYaCzCeh2pUTD9+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:K9XNFy46q16ODDWHeY9QsHQz5h73UN00zPHpbC2F8vnR6gsHTdt9mhhDUul3HUCRtpt4OegOt82lSFBgtx/2eHiNPnCtv2+i327HkW9+Z2Wu,iv:PwhubE0QT/W7OJFV5ra4aT9XoCJYjyr6tb53Vos/9Pk=,tag:fLaAj1hl1fABEo4D9yIlcQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:L4eTAzBnNK32vhCPWjVPoJmLG9MyL+I710k+zpuf91gLXvlQScvu7BJ5yQ+vBG4TUHNvcf7i5j1N,iv:1yvMuSkg4KVxexaeyVhAAYRfXHQeQsu0aqlRHe315u4=,tag:VXdiv3o6BDjQrFUP7zCFPA==,type:str]
    #ENC[AES256_GCM,data:wj4nv3zCpwVQkjY2grvm9qh0bCrKbHtwpeCdpIrmLfH1EELzIpxDRqaQTZjTZkfu8cVoPQreTuAVNmQ0h7fmzbxiG55A7OtEhYQlM734lHfUhymzCU0r3yjpEiWiZ6893RzrHA==,iv:bWaOk7oe0HXb+irCNeFS/iocqpd8I4bED9EczMIDsJY=,tag:FG3jwpGuXqVENGCRw7QRRg==,type:comment]
    #ENC[AES256_GCM,data:FsgI8pUv+7DGsi/sJsg11J3RgWi36MO+TSxdbuZGCXytGf2h3s9g0J9M7J44Zt8ViRJ+EBi4rZuAuMcjwFfIAjjZkFNTfhaIFXXdb/CytvqC/0LvPusJDyi0h/bfi6c=,iv:jsObrcTr+wOKtcYLHo65tEtgd2Brtqw/1CzUjbV+ZPY=,tag:fdl4zL4y2HZzc0+/Hk2ONA==,type:comment]
    #ENC[AES256_GCM,data:W2rn1w3MxvUMXn3DBDFRj3zsTZH2lt1nOkjZ73yAUYJNBcN+m36sMfUuJiGSGkwsbsxT2J4TGTsAficUR+NmTaV4U8NSxCcpTcI+z3m/vwKjnfkM5w==,iv:u3dK1+KCPNpX4VId695RjQdzZmawpJRQpN+DwAdW+ns=,tag:FvxqaJkxPwzDaxTTu+pXXw==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:QcV+hdrczHSHg9lOLaeE5ns6,iv:boy0p/r/CnpVLJnn9qQW01s8waRC0hryuCAoyqe3l2g=,tag:R2LLVt5bmZ/8tLJ9JMRdiw==,type:str]
    #ENC[AES256_GCM,data:iRHkdEd75E6z+w7xRiWA8xPQCBD0nfZ+6kGOh9V6p3Q1bA==,iv:88I5U85TbeVwsPH+oy5xBocNKWvUa2W9KP0w2n33NmA=,tag:ol2hs3D633gHuRFd8e+9bg==,type:comment]
    #ENC[AES256_GCM,data:fnbg54r+athsDB5glNRJjkiw6W9zahhoxm/HfiBBOoi6vmtCsXa9kMVdi6z04/g6oBPPr4FEdlB/gNQceQ5xCTxOwnyWzg==,iv:P5A3qGtGrU+kA/upx2OtVxcEcaoRlegJmn0UsGus/GE=,tag:YaXcKiWvJ9IfaAOWe5jyBg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:KPQpRUcz/A==,iv:tmX2kr1gMfdzY0midsJc9qs9T3TQFUNhC7HcYIMZlS8=,tag:eVUD/IUq7QhkUgx/jmXiAg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1/2uzaEDtVqyEH+9veniPCM8MA==,iv:f61yzywWMxD25T6kQ0QeZp4Q7QVUepXCDDbp4giSy6U=,tag:pJw5eNqAaXmSMTzQlqXsIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dE0wazlacmZxWURHWUFm
            WnloYWRXeStaTkhYZUVEYU5uTFc3cXA3bkQ0ClQ5aHRnZ2tSblYvc2N6Zi9tRGVG
            QkRFZ0VGK1VwVGZLSEJ0V2JvamVzb1kKLS0tIERFdmNFY2NieldvTkZSZlhHa2kv
            VDVQZUZmYUMvMmxTdklpR1B5R3VibHMKTu+vP+c4sZnrr+4ZkCDCfrA1M2qaiwOu
            I8ck8w0mRKn26AXIHpqGnVPprCCYKxO4ZbjFaUNNYDrV4/ifrjDH9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T06:06:38Z"
    mac: ENC[AES256_GCM,data:HDWen//KGQVXGO8Je7zcUx0OUF1Izg3dsTVnfzjj7W/EbWxIhf0nJ2l5Daxtbg0ulUgu4xkaJxT7mDgGczcXKihXnja2qtvQB3Fxzaah+Gm6p/0leJcD3JoyVad/JIYVoAb1IM9tChl59YKkmSWDF0PKUbajdlZWAVh0N/djfbY=,iv:+UMNFW774Mtr3cyO2kurOlyDraIhuwiPR90mXRJx8kc=,tag:tBFdQ3cYaCzCeh2pUTD9+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
