---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt
spec:
  sourcePVC: zigbee2mqtt-data
  trigger:
    schedule: 0 0 * * *
    #schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot 
    repository: zigbee2mqtt-restic-secret
    cacheStorageClassName: "openebs-hostpath"
    cacheAccessModes: [ReadWriteOnce]
    cacheCapacity: "1Gi"
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "zigbee2mqtt-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Clone
    repository: zigbee2mqtt-restic-secret
    # cacheStorageClassName: openebs-hostpath
    # cacheCapacity: 8Gi
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    accessModes:
      - ReadWriteOnce
    capacity: 512Mi