---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  sourcePVC: data-zigbee2mqtt-0
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: zigbee2mqtt-restic-secret
    retain:
      daily: 14
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    cacheStorageClassName: local-hostpath
