---
apiVersion: batch/v1
kind: Job
metadata:
  name: "${jobName}"
  namespace: "default"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      containers:
        - name: disk-wipe
          image: ghcr.io/linuxcontainers/alpine:latest
          securityContext:
            privileged: true
          resources: {}
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache sgdisk util-linux parted;      
              clear;    
              sgdisk --zap-all ${ceph_disk};              
              dd if=/dev/zero bs=1k count=10000 oflag=direct seek=0 of=${ceph_disk};
              blkdiscard ${ceph_disk};
              partprobe ${ceph_disk};
