# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-s3-aws-creds
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:o5YCRPgs9lk=,iv:jBBM/e4//6cq04rUSezh1rXmPQOPVH6BFCEZmShiEWI=,tag:6lMczfs0JoVnuCsST9sEeQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kInq4ZOSDKX9UEhUQdMyyAck97tWSFoiQzLNEaxLLoQCHxGhPd0Qew==,iv:Shqzuwa6TErGTNbX+spfUFdOmgY8s+2Vmp+LQSToLh8=,tag:MjlWyALUpvAu5Hqd6cYB4w==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:M70fox6345UJqZdkSiB7PIgDDbaT3cQ+4uSnsddL3zE=,iv:iL6cXD4HzwWDtcmQMFVuC6i96ZDbQNvnvYEWU0HCqY4=,tag:1w752fXJGMOdlP/xB/zOVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-18T05:27:40Z"
    mac: ENC[AES256_GCM,data:jCppd+jWcn1lxRg8dF21geOE/uQaz+0kMGg40jwxwdWLeT3lEh5n+0myvYmycyBa8gXf5g/+R4VutTZYbE9sUDoRieeLUI8xkbi+OY6HL8jjljWl92c1rI0MYjg9jIPyyl4nItK/l8LMkdXN3/QCMggmiJku0plgodzr1Dr0MNk=,iv:eSoCUYsokypsraCldcdt5mNWNeaxDLlDQNbt2hrcw7c=,tag:krnF9imwG9XXi7sJKZsMjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
