---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-node1
spec:
  restartPolicy: Never
  nodeName: node1
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.19.1@sha256:0e3067295cc20dafbd4cf63789ccc71858ad555f3998200ca10b271328c7285e
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: /dev/sdb
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-node2
spec:
  restartPolicy: Never
  nodeName: node2
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.19.1@sha256:0e3067295cc20dafbd4cf63789ccc71858ad555f3998200ca10b271328c7285e
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: /dev/sdb
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-node3
spec:
  restartPolicy: Never
  nodeName: node3
  containers:
    - name: disk-wipe
      image: ghcr.io/onedr0p/alpine:3.19.1@sha256:0e3067295cc20dafbd4cf63789ccc71858ad555f3998200ca10b271328c7285e
      securityContext:
        privileged: true
      resources: {}
      env:
        - name: CEPH_DISK
          value: /dev/sdb
      command:
        [
          "/bin/sh",
          "-c"
        ]
      args:
        - apk add --no-cache sgdisk util-linux parted;
          sgdisk --zap-all $CEPH_DISK;
          blkdiscard $CEPH_DISK;
          dd if=/dev/zero bs=1M count=10000 oflag=direct of=$CEPH_DISK;
          partprobe $CEPH_DISK;
          rm -rf /mnt/host_var/lib/rook
      volumeMounts:
        - mountPath: /mnt/host_var
          name: host-var
  volumes:
    - name: host-var
      hostPath:
        path: /var
