apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ohVfmtda9iINsLJyF16CqpLmFv8onhJ+FDLIoyj/Ba07/cHTDO7o2w==,iv:GRxLMHTgZmtwMXEc4RDNgPzvUK7A91LiNYfeR+GNRCo=,tag:WnpdTCiscJOHULaJ99wClQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TG1vOURVcmZia3hMWnU3
            ZG5PcmkvUC9YY2lJTEZZK3FkSFowSXdDS3lFCktJVitMbWNaQ0NIeXZYNmhnT1hv
            Ym9YTnJlODZFY0tiWS9oQ2hXV1p1R3MKLS0tIC9hUlVwYUppYVI4SE5CcW1lODZs
            dHdodEdrR21XQkw0clE2aksxUnA2QzQKbZYqpcuPV8T7gzEQ5JK1kWBozGeNoULc
            IaLtRx4HaypatHYxy9NP8ZaD+GZGZQpV1yeUs6JfKOrmv1jSO6TimQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T06:27:19Z"
    mac: ENC[AES256_GCM,data:nh2ZqCWjv+5GntWGC3c6jcedzC6K4l/b3QbPuDVPBDzAY0KDBduBUs+6LDJvwyHh+8ljqwM9kLsDL+SGfBYK23hP3naE7htNE4VI0G8dnidsX/LBTXOxwhnd1tERfvA8XHH6KwuWSP+o+epbXWfD4K+oBWKVVPV40B1Y1tId0so=,iv:bLUN+hRte02rKzYNBMaKVKDjJLwpi1Md4Pyy6fooS08=,tag:3Fw1GbSNLMTGGNRyNp++eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
