apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:D3Ti7p98jLjhpz+Kgjua6WbK1Ev/GZngdi4uV/ygYshRo8gYPHrhvw==,iv:HUy3KTh31rRJ9207/64RIZtwO9SQ2qmmNWbm1lMV7o4=,tag:lUuZ0KM8kYnHR7lSeqK9eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN2FyVGR4R2ZsS28rRVpD
            Smp4cmJpVGhVSHJ3WXNVaDBVb284SVFKcUc4CkZlNWhUTjd1WXpUaFhTUEZSeDM1
            WHlJdHFCTEFmS2FDU3EwRE1WdU1GdnMKLS0tIEZLTTVPTmVBVW5mQjRkekRwWWVP
            NjZ2bWRSL3NJQVJOL0NyWkxkNDlSOTgKNsEbxrpoSORoceWEJZBcVYfrTwoX1sXN
            D6pB8RntkqWX9V2eoqcAx3eyOSeLOJRIDf0A8Dou3YAP5+AbB9Zkng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T08:51:26Z"
    mac: ENC[AES256_GCM,data:g2/cb5jecS56qXL3kEWnA6uuDqtCBlmA1s3rzIY1SJlBvfdcxrrXdoWHY38+1aZvRIrcwWDxCkXEIWuAbmKDpYDkJpeH9lqrsrq6e4UDxAU7dmALOpC8uSSz6xsSG6sbydNMozI7wqKVvJsDOLGk2sscRjHsh/U5ZCGRW5OQ+gQ=,iv:QkCY1YkLXh+3HmezyMWQdLx8MT7tPepLwIcTOhmFSLs=,tag:ryEOi6rs3u6OxT9O/Pey3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
