apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ybEvlJnaYOM0pfKjH4kRxbxfbktg2G68T4XvHb8rplacQR/P9aZFkQ==,iv:cTAA3buFSGvS/+i6DgsfF92L8Jr2gX/eO6lFCnoIPxM=,tag:aZu5a9CDbbzd8Va4kDvmNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NzNVeE5TTGU5S00zN2lX
            VHhhMW44aDNwdVZBSGpuelFnS3ZkbnptUlQ4ClNSTVhJdFpSb1d6dWJta0h1eFJu
            MzI5bWxJQkhzdlBtbDR3aEZGdEhxN2cKLS0tIGVRRFJGMjlxSWJXYUFoZjlLZ3pa
            eWxXWkFPZEZWTEJWVXBOczd2OFdTdFkKGUsW5gaKKdxf+BT6KaryxF6CJ8vH/g8c
            sy4+lR2e5rKY9zJplw1cYPTOSDBf/idxJVYNRgemUiKrkl+VNFkmwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-18T05:49:31Z"
    mac: ENC[AES256_GCM,data:nULX8AtdY5RRIHhR4IRtrTn7D5Bc/wShNb/bFhUbOgVHS4W6YL1qchrVDudmKR5krBjpNYf2oMXXMhwrt5otA7MheAF0eG43kiiUgrr+s4OqdLudZyPhtF2c/iu+Y8kMhBllPY/tMIrAbgB8jP/XxJVwvqDTI90kl56IvpQwJUk=,iv:aFRATMQ5wKlNluewysziv7Irv2ZSVGCgLJNDFHxj0bE=,tag:xuaIG84oBDJURRJTN34WvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
