---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  interval: 30m
  chart:
    spec:
      chart: k10
      version: 6.5.4
      sourceRef:
        kind: HelmRepository
        name: kasten
        namespace: flux-system
      interval: 30m
  values:
    crds:
      install: true

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
    cluster-name: home-cluster
    grafana:
      enabled: false
    backgroundController:
      serviceMonitor:
        enabled: true
    injectKanisterSidecar:
      enabled: true
      namespaceSelector:
        matchLabels:
          k10/injectKanisterSidecar: "true"
    # externalGateway:
    #   create: true
    auth:
      # basicAuth:
      #   enabled: true
      #   htpasswd: ${SECRET_K10_AUTH}
      tokenAuth:
        enabled: true
    ingress:
      create: true
      tls:
        enabled: false
        secretName: "k10.f-wi.com"
      class: "internal" #Ingress controller type
      host: "k10.f-wi.com"
      pathType: Prefix



    eula:
      accept: true #true value if EULA accepted
      company: f-wi
      email: k10@f-wi.com
    license: "" #base64 encoded string provided by Kasten
    logLevel: debug
    # secrets:
    #   awsAccessKeyId: 'admin'
    #   awsSecretAccessKey: 'admin'
    # metering:
    #   awsRegion: 'us-east-1'
