---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-openwakeword
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      wyoming-openwakeword:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        
        pod:
          labels:
            ingress.home.arpa/nginx-internal: allow
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place

        containers:
          app:
            image:
              repository: rhasspy/wyoming-openwakeword
              tag: 1.10.0
            args:
              - --preload-model 'ok_nabu'

            resources:
              limits:
                cpu: 12000m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi

    service:
      app:
        controller: wyoming-openwakeword
        ports:
          http:
            port: 10400

    # ingress:
    #   app:
    #     className: "internal"
    #     hosts:
    #       - host: &hostName "wyoming-openwakeword.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: app
    #               port: http
    #     tls:
    #       - hosts:
    #           - *hostName

    persistence:
      data:
        existingClaim: wyoming-openwakeword-data
        advancedMounts:
          wyoming-openwakeword:
            app:
              - path: /data