---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "wyoming-openwakeword-data"
spec:
  accessModes:
    - ReadWriteOnce
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "wyoming-openwakeword-bootstrap"
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
