---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
commonAnnotations:
  meta.helm.sh/release-name: kubelet-csr-approver
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm
resources:
  - ./helmrelease.yaml

configMapGenerator:
  - name: kubelet-csr-approver-values
    files:
      - values.yaml=./values.yaml

configurations:
  - kustomizeconfig.yaml
