---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-user
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cluster-user-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: weavegitops
        property: username
    - secretKey: password
      remoteRef:
        key: weavegitops
        property: password
