apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: $2b$10$ZISXLOKHx.PLA3aWuMQZ0e85NdAsS4F2fut1OijRrhGgOun/ag6SW
    username: admin
type: Opaque
