---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-repositories
  namespace: &namespace flux-system
spec:
  targetNamespace: *namespace
  interval: 1h
  path: ./kubernetes/flux/repositories
  prune: true
  wait: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: flux-repositories
      namespace: flux-system 
  wait: true
  patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
      spec:
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-settings
    target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
      labelSelector: substitution.flux.home.arpa/disabled notin (true)

