---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      whisper:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        
        pod:
          labels:
            ingress.home.arpa/nginx-internal: allow
            egress.home.arpa/world: allow
            egress.home.arpa/kubedns: allow # FIXME: Remove when clusterNetworkPolicy is in place

        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 2.4.0 
            args:
              - --model 
              - small-int8
              - --language
              - de

            resources:
              limits:
                cpu: 12000m
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi

    service:
      app:
        controller: whisper
        ports:
          http:
            port: 10300

    # ingress:
    #   app:
    #     className: "internal"
    #     hosts:
    #       - host: &hostName "whisper.${SECRET_DOMAIN}"
    #         paths:
    #           - path: /
    #             service:
    #               identifier: app
    #               port: http
    #     tls:
    #       - hosts:
    #           - *hostName

    persistence:
      data:
        existingClaim: whisper-data
        advancedMounts:
          whisper:
            app:
              - path: /data