apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:Q81JvbNLVxlmv5dAIVPPStAKk79NE8cIwvNrNvhuRiA8/DIZCzKTFzmKD0VwX/42++4a2e1UsHgKKxU8wd731oMhjHwPI6Wp2ZTIgAXOuTpUj+z5O2s8Tr1+7KaizoZxYopwfBkE/KmuRYp5wUHGlMQoNEI6DcEHZ23aaUwjMKmZC+idoq5nKNXMBAoSXMOrbTW+U88=,iv:ZgmHvVYU2z9RlmfY+B5uFJ9GFChkzHvRLFKVnllpFpk=,tag:+D/Q8mrnrNtJ5rbrLX5wtw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN3N3aDNLZTBYOXZ3Q0lp
            Z0NZNEpXVlp3SXI4c1lqZTlmQkM1Vi9IVzEwCjIzM2toc3VpL0lyMk43QWR0QjF4
            TDd1WmtEOUZNaVNnaEVYR3RBdTJyaGsKLS0tIG85ejFKVUg4S0xKbHFVYk5lcFhC
            bTlOcEtaYUkrNjRTOTMrUHZNbDIwT0EK1+xYqLLe1Kr2mN1mIWNw2W4uUEAoR9gL
            JUcoGRicxlV38qxZ2/Z5AfCbs+i1yalUI4zo0rjsPMj543oakgUqnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T08:38:25Z"
    mac: ENC[AES256_GCM,data:79rszMGTDHO35gGX9SdnHQXosMetLQreK/GCrEBO/KcqxOcxqDUo03p2LoZddMXTdQRcIqnqpxokqzi6vt+nzVmoj//6x3yE4BXhlJKoQpf3lXVSyKKGUdFn1BGYfHOyuR6NZVHqAa66Rh0aNTfkrCYVYsx4W+eRvV6IdU9U00A=,iv:RyZa37hhGMGcpSlrTdrNevTDjCv51LY4c/gc5AIQbRc=,tag:G74SaV2XaG+S+o8JYoy7dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
