apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:tYBQqGdpYfYC0zGzGCAh0CoIjmjEGeSRfw22hmVp5TJI7moe3TE0tryCtiDyXEA1JWohpsZBpIyC/m2G9D7dcVcDbu9sVhtO9/PptTmi0HkwU/M5XWipMM2kIYjE+t+D3HG1iJqOoOaSvj/C+LTItNBSZFdlaszXpz8DaPc1aIJpNZ9Q3DLKHotAMA==,iv:wvLNsTr9FJA881OGx8d9s7q6x3aiRLvKXHpSG76WjPg=,tag:b3jmf8rnpwWo4AIQNRM4Fg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN3N3aDNLZTBYOXZ3Q0lp
            Z0NZNEpXVlp3SXI4c1lqZTlmQkM1Vi9IVzEwCjIzM2toc3VpL0lyMk43QWR0QjF4
            TDd1WmtEOUZNaVNnaEVYR3RBdTJyaGsKLS0tIG85ejFKVUg4S0xKbHFVYk5lcFhC
            bTlOcEtaYUkrNjRTOTMrUHZNbDIwT0EK1+xYqLLe1Kr2mN1mIWNw2W4uUEAoR9gL
            JUcoGRicxlV38qxZ2/Z5AfCbs+i1yalUI4zo0rjsPMj543oakgUqnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T08:32:30Z"
    mac: ENC[AES256_GCM,data:xOBjpwdTwHdgpw/Zl0dj/fZrLOk0fu+LRyDDxwqkKR6Zz5zG6zBOwg1OoY1cYsMTYrGZs+d4QfJroq4upfbj/rLEEdMP4wi5GmNKujSExejTvxj16Wz+TFaxQBqNNlwqB2UojXZPDapEH2Wuob6ZOwOBve5bk/U3DfQwA6iGKbs=,iv:CBhxTh4ZEwm9pMqwUZuCq58fjRE8lzOYZOTEXpvHoUk=,tag:aLLvcjxhplYXOfn3wbB2JA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
