apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-secret
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:4Rtv+rIE86GHnqN62foebszu5/2zNDSNsACdT/NK8m8lAF5mIUVVzE6qbcs3h2xHJiV607APCKJAARZAwtuE9/7RMlCq9c7FpgeIZaT1bf2RrTR2Ak7Yrotr1Og4eOOUd6x64acRWlS6TmQpSCbxnzUrLbPkDropaq7+5w==,iv:OKL1R3PXYsyi8/16cqYWbKGbrxfQ/L1lV7tGnPVEnQk=,tag:oV4KVvelqPYyil76KWIaAg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN3N3aDNLZTBYOXZ3Q0lp
            Z0NZNEpXVlp3SXI4c1lqZTlmQkM1Vi9IVzEwCjIzM2toc3VpL0lyMk43QWR0QjF4
            TDd1WmtEOUZNaVNnaEVYR3RBdTJyaGsKLS0tIG85ejFKVUg4S0xKbHFVYk5lcFhC
            bTlOcEtaYUkrNjRTOTMrUHZNbDIwT0EK1+xYqLLe1Kr2mN1mIWNw2W4uUEAoR9gL
            JUcoGRicxlV38qxZ2/Z5AfCbs+i1yalUI4zo0rjsPMj543oakgUqnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-09T07:43:14Z"
    mac: ENC[AES256_GCM,data:U5AURTqiO48ZKTsjPbGC4zFmUHoP7SB3DVvixf4q7hZ39vhZHl5wn5DeoPUVG+oQpydxfHvkQWrOdQzVGAc2Xl3ONXFvZ3NOuDPYXZN4xiu8eSsc/QFx/gadwSSgws8RoBBsQRb4/byAZUpyJMnIbkz2xfTkCZreLqAVJnbBC94=,iv:Gb08kSGt3WQ0Vo0XEThNCy2QEtWnZP+OfQHIbCJQlXY=,tag:2Inj65MJ2pXnrchfATlPng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
