apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:eUkoXEiEiF4=,iv:Mmn7fAuvJ+loOqwN7vhAnl8F0/UIJPcm6b02FmfVq14=,tag:s/J3acLUz9H12KSWW+uuJw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UXXUjq6/ctuGEamT0UMf0Zv56wNOWA==,iv:VHDCBn3poKDJuYtozlpNQRqz3QbuB/cg6DJyHP8v8OA=,tag:gi7uZAslNIy1MUBBQeilVw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:oqdi0RCvZTDZ+RfVbksoBBvUeD7Yx3XDkDYUSfGpTnk73kEw,iv:/KKPV0tUrF1q3JbjLQaU7km08NT4VmAO4BJ5wDjTa3E=,tag:kqk5W1D/XAFc4L4zSzOM/Q==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:IbPZIhRfBsReCavnkSNi0B7vJSyXmmwfAIumGXLfs2UJ+yFRHqDn01jeHK+xhbOEK4oGcrlpfXYC5QCzwB02Hg==,iv:zfvCP1WEWd7EngU6cvqpfMXYOcodF5osKpq69sWdF3M=,tag:h8kaMddbREvZZo67Ewg3zA==,type:str]
    SECRET_SENDGRID_API_KEY: ENC[AES256_GCM,data:QyBYvsuDumeOIrsdm6LH07Ie5HFweZDBtjO8stK+f/8FqZ5f/pLmAB6fZpyg42swfU60OoiXmjuaAVggmJmgYGR3JAt+,iv:/EfHKq+GvvXkCLwfcAn61SMEDxBluBIF/pKgp5s2iPc=,tag:MPOYA+Mu0hDoTQxdlSiiow==,type:str]
    SECRET_K10_AUTH: ENC[AES256_GCM,data:HESR0W5QVsYIGbwvbayhtt3E4HZG5dZy73m1kbwSmnd5A9pnY9gxNed2,iv:YdjtLC7kTHvdrhwxhhquJ0Y8L741KU7pflyHpnmsGqE=,tag:baTzPeDLDs9Rijv7f6Cq2g==,type:str]
    SECRET_K10_COMPANY: ENC[AES256_GCM,data:jxXhlA==,iv:9FQTBF1FtPBy5KKnUYgdAf9xQvQrbkjjd8Lbga6uyx4=,tag:7Q2wz5gmDmlE2XQH3DYofg==,type:str]
    SECRET_K10_EMAIL: ENC[AES256_GCM,data:FzHho+IkBvMQVhNM,iv:ky/iqXPAeEMtLUvu5NEiLO506EnneZQZ32sWx2+Nor4=,tag:Ru7w/gCOQfuLTS079sEdkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRzVqSnBsUGM5TUV6c2tr
            YjgxMkhwS0cweTFPMVdscUZ3Rk02NFhvYVVFCmsybSt4RHdWeWJLbjJKMnpnVlpG
            Tk10ZTVnb1RnaUpMWTVjVTc2WU9tVjgKLS0tIFRRaGpLa2VZaitpK3ptZEhEeDBj
            UEVZTmtoWDVuWUxrMHhYbThnclQyMDQKPC/AthRPkcFu26mS+A4Eky/znktarOVK
            2ouO99KH7snK/VsTyQqK+VHyz9RPaZR8EYlr60ZgtG+FQfQ3LsiJdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-12T05:12:32Z"
    mac: ENC[AES256_GCM,data:4TJXPDU63C2SIy2HuJI/WbjX/sHW1kzErv6pIwsl+2EE0+gkFdJmjAecvjNj0qB/V7auHv4y0G6fWM1REKKq0uEuZlyc87+PLazWyWLKbp5swBYUjl3wpq1MxOxb64eM5H1MzPwYwVvi4KJ78WOeVm2JZOTonp1c60cJ2WDorkg=,iv:815mTgO6EVVvHtRHQtH67Jlynr0NdpoNaRht0npsL/4=,tag:t20pLXAmpZsDVbMo0mL91Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
