apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Ksr4Xo+XFNQy1PIpdp0xW4hqhaZkY1Dh1c/4XSMNaMp8iUZRm6tTfMcPKgl2KPWRUjb3Yee5f+N8jJDlo2GuEML+LjO9zSXaEoBFxiuq+NOcUInTogZsPhB1Ai8wRg==,iv:0ETlA5zPl2gE2l+YFmLp1JHhcJWTIU6kXFKbiyh1NuU=,tag:bU2sT54kpUes36gGQd5qeA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:pHpjA4NAZVU=,iv:RWTg9QnHjkluKdSUWBdbSs8tBZDABqM9r39yGBh7hSY=,tag:iRjdox5LMpYziqRkiZCYag==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Fwv58501S4l1IbFDfG1hJBTTV5nUhQ==,iv:z63r8bFe52e9ylCnZ6rn7/fNOb9w9Xn/6E6jUYcyALs=,tag:NcKR3bHQ10ck6DPmL12rKg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/JYJwzaawUHKkK1OEXcpj8bg0gkTBTM2sNzz4sWYAle26xxk,iv:LuoA8BPJfSTK14w8t7dsc/C7jm/3OZo5S9Eonv5FvPg=,tag:HzxalnNWJEzONu15aAjvPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTjhVWElhdWFZMCtleldr
            MlVqaGVrbFJhNExrOHlUZUFDSUJPQlBXU2tRCnF4bitlTElvOVg0dEw5cUFGaDN1
            azh3dXMyRk45Nk1MSEo4SkpZWHBqOW8KLS0tIGhoYmZSbTB2TEJCWEt6WW5rS3NP
            SktHMnpaWDVKQkttVFE0R0twdDgrbk0KKZa3Ohooej7g5ulRrTTcaBv52LihmfT0
            L5LfqalQUPbbW8G7UcCkqWMvDaleH8HP4X+NGRPNgsCF+HZyd0X/cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-17T08:01:31Z"
    mac: ENC[AES256_GCM,data:rBIvYOYJKuXdjKD/2tHaP2jYFDoH9fzqvF5opNpkbjLVOcBNVJoGqUD55vcwEln1sfcP+2r4Kkas+63htc8jigm/y6mUBhdaYnsCEIgJqcvOzW3fhJVO46F2sfq0B2ZOUqHd8GfbJ2xqG4idqknCoSKC/h1DUAOEJsDY1Y5KqOc=,iv:hrd5NERd/gRslJpsLrr2s/kVMquUpabnSe5PecBombU=,tag:lUcq0p4Ia0uwZK6i6P58Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
