---
originRequest:
  originServerName: "external.f-wi.com"

ingress:
  - hostname: "f-wi.com"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.f-wi.com"
    service: *svc
  - service: http_status:404
