---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    redis:
      enabled: false
      address: redis.database.svc.cluster.local:6379
      password: redis
      database: 0
      required: true
      connectionAttempts: 10
      connectionCooldown: 3s
