---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: 12.2.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    redis:
      enabled: false
      address: redis.database.svc.cluster.local:6379
      creds:
        redisPassword: redis
      password: redis
      database: 0
      required: true
      connectionAttempts: 10
      connectionCooldown: 3s
    prometheus:
      enable: true
      path: /metrics
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.10.221"
    upstream:
      default:
        - 10.45.0.1
        - 8.8.8.8
    upstreamTimeout: 1s
    blocking:
      blackLists:
        - name: ads
          lists:
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://mirror1.malwaredomains.com/files/justdomains
            - http://sysctl.org/cameleon/hosts
            - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
       # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - ads

    ingress:
      main:
        enabled: true