---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  values:
    redis:
      enabled: false
      address: redis.database.svc.cluster.local:6379
      creds:
        redisPassword: redis
      password: redis
      database: 0
      required: true
      connectionAttempts: 10
      connectionCooldown: 3s
    prometheus:
      enable: true
      path: /metrics
    domain: "${SECRET_DOMAIN}"
    ttl: 1
    service:
      main:
        enabled: true
        ports:
        main:
          enabled: true
          port: 4000
          protocol: http
          targetPort: 4000
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.10.221"
      dnstcp:
        enabled: true
        ports:
          dnstcp:
            enabled: true
            port: 53
            targetPort: 53
      dnsudp:
        enabled: true
        ports:
          dnsudp:
            enabled: true
            port: 53
            protocol: udp
            targetPort: 53
      dot:
        enabled: true
        ports:
          dot:
            enabled: true
            port: 853
            protocol: tcp
            targetPort: 853
      https:
        enabled: true
        ports:
          https:
            enabled: true
            port: 4443
            protocol: https
            targetPort: 4443
      k8sgateway:
        enabled: true
        ports:
          k8sgateway:
            enabled: true
            port: 5353
            protocol: udp
            targetPort: 5353
    upstream:
      default:
        - 10.45.0.1
        - 8.8.8.8
    upstreamTimeout: 1s
    blocking:
      blackLists:
        - name: ads
          lists:
            - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            - https://mirror1.malwaredomains.com/files/justdomains
            - http://sysctl.org/cameleon/hosts
            - https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
            - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
       # -- Blocky clientGroupsBlock
      clientGroupsBlock:
        - name: default
          groups:
            - ads

    ingress:
      main:
        enabled: true