---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./flux-operator/ks.yaml
  - ./weave-gitops/ks.yaml
components:
  - ../../components/namespace
  - ../../components/flux/globals
  - ../../components/flux/sops
  # - ../../components/flux/alerts

