---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./namespace.yaml
  - ./flux-operator/ks.yaml
  - ./weave-gitops/ks.yaml
# components:
#   - ../../components/flux/sops
#   - ../../components/flux/alerts

