---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
