---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: security
spec:
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:14.8
        env:
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
        envFrom:
          - secretRef:
              name: vaultwarden-postgres
