---
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    volsync.backube/privileged-movers: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    kustomize.toolkit.fluxcd.io/prune: disabled
