---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  # - ./volsync.yaml
  - ./postgres-secret.sops.yaml
  - ./ssh.secret.sops.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant
