---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "home-assistant-config"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "home-assistant-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-5Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
