# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:/A1yYxa9qXRn2ww=,iv:gAG5T+Cq6iNYiS+pL6wief7HbqdJHnUaQ7Kw4yk6YkA=,tag:01teMCohXIih0Kn4vpxL9g==,type:comment]
    GH_DEPLOY_KEY: ENC[AES256_GCM,data:lJI8GxBSgs9i+DDvaCLTmkY27KrxkJ3P5PsRAfjG1Dor+6zLue0Yif6Q1NniQzjFlXQ=,iv:0z32tR1vIlOGf/P9A5ob2EEtVVMGDNhW/+llAFVzCn8=,tag:qLw6l3RVQs4OiAP742Uqmw==,type:str]
    #ENC[AES256_GCM,data:KhOV9rZF7ZnZG69RAG78,iv:r6nUGDnikjDRK+e0dQkiNdM1+0MhIWWWqe7fdSxThHw=,tag:OYI/f+EruJfopv/wGayrkQ==,type:comment]
    #ENC[AES256_GCM,data:/vtbBzWj4jDqiOXrO+Os3drG211riwo+fgHGBuN4LefMXFplTtDgRqiVhkk=,iv:MWnuvliiRROtW7rgprq1nYn7Br4JevafOVOcoFfCWLc=,tag:0++YOx7fxQx8q+9rK+f9XA==,type:comment]
    #ENC[AES256_GCM,data:Z/AOkF55AZW/rXC+fwRPpSj+maszyuqb5OsNcVAyaCMImXvGw3HYgkC3tzX1UqxlgBkA,iv:NNNoe4Nhelpjq6UpTxnEaJ7C+vZO1PtQJGtiJFvgyMA=,tag:Q4F9+ttPoG95A92POYzB0w==,type:comment]
    SECRET_EXTERNAL_URL: ENC[AES256_GCM,data:uim7mVxTqMZiI2bujazhml/chP3tQs69Dgcpgxttdsa5xIxsQ4wC,iv:ICD4bPeUZMeVRFM45yQIWAd+YpDHQgEvK4X2+e0gfZo=,tag:LtzfjqUgTL8i5CUsa2wlNQ==,type:str]
    #ENC[AES256_GCM,data:haqJ6GkMd6iJ+54RjDmFZh1o3rZeeRhPNYlTUU2KtUoyOB+6GWlhhA==,iv:r/ew/NDycjuI1KTLQIk9KBA6iXF2t9WlULXbuO+LV10=,tag:oPtcFb+UYBtV8EcjdvA5ag==,type:comment]
    #ENC[AES256_GCM,data:SETdK67HalqQtHaYBeYQOtr5qQym,iv:7eo0vCsTq1OflsEnFROzKyvtmMWbADpVBlaiDAz0Ht4=,tag:MhPB8e8XbQC7xH3QC/8qtw==,type:comment]
    SECRET_ZONE_HOME_HOUSE_NUMBER: ENC[AES256_GCM,data:CEg=,iv:cluxFyFITdu/TfPK3Ckmcg5bGwev3xD0kRCDm2+QnOE=,tag:6tj2zUOHbADfWxLoxFee5Q==,type:str]
    SECRET_ZONE_HOME_POSTAL_CODE: ENC[AES256_GCM,data:sX+8w40=,iv:Pydq/5gTB6mM3vswO3NgjZG5jQxcFZq6zBCvRI2cgCw=,tag:8Qf/GC96+Mv7QQw8quPm6g==,type:str]
    SECRET_ZONE_HOME_ELEVATION: ENC[AES256_GCM,data:vEd4,iv:OeSCkt0yxMD8I/I6nydzxjHoVoQ7WdkQg73IcOEDMNg=,tag:HbVuLWBgtKIVohLm+/KLKA==,type:str]
    #ENC[AES256_GCM,data:I+ShD8wnETBM4LbZOGQB3Iy/ZYwYR5rYxVdel/F9GXAehMvdby2Iej7EvoIfWmXq32O7BoCx21bHr4A=,iv:Hgg+3/rN8g0DJP0V5kLrTXPMht2Q5OgLgMVX1zIDXuM=,tag:ejC0ZY83lj2ocT2clhnH4w==,type:comment]
    #ENC[AES256_GCM,data:WjFMvwsztJmTCQvPz6zV/EUGSIYRiNNde44uDWWc5mCdLzYryTXD6WuFrwBszX/vnpy6H70yGXfRbL/Grw==,iv:9ATYj7F384WdN50m2qmQzkpQ9n9wNZPnAiyd4Dvnbh0=,tag:rcoxP7OyRr6HP2+0+62gXw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T13:00:15Z"
    mac: ENC[AES256_GCM,data:JEMGwurkTV2qTxIEDtCmFmDS4N7UIZju0YEJlgTkXTkkuzUnbmVWzQft6fQr3LabH1WxmzxHJEbDLUAMz6YUUnvGfvaJCzj/+OvmY4EgCmfhyx4i7P5zPhrdFMCDmrNJ8OFR59NyGT8sP1B7zz9Vwj0+zvngwV58x39pnCCd4Wg=,iv:n//t5dtsUhY/vI/cnbl16kXOeAS8FWYG9owUG9JXVp0=,tag:WliWWACGM+MBV5YGygietQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PWVk8p/tDrTsCATUYTjrvn5jdXRXzTQujeLp1HxDS/VSDd0phnU4vOvB89oJ38+rWAhkJo2+TlUbDM74mIPkufdodIav9a8O1uMkExwLKk/g,iv:Udn4aZ3Qv26hsLN8gwPjIc/WbmZ1OD5d/eBUoxENwRk=,tag:dafG1Er2wXtIeYS8CwFvDw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:BA3IcjdQikM3WWgn2YHdcm15n6fUBP2GCHkPlWWX8wrVJFqDZareJ7JlS2T+ZlH88fM=,iv:J1LnrNbkp1LAfwrNgxlhOuPPAm7+kjSCXAlAgfTW7Zw=,tag:WfxrGxHPvB/s9w+or4g8lA==,type:str]
    #ENC[AES256_GCM,data:pQWk7bQSBQhI5vkhFcosRY5Q5unXCyu5qNGj7jf9vxWxzVSZ7KyyVAFntpTo1jLEMDIBwuGgh8cuRE8XEx2Zm0lNpwIdAY3vvLI3hidWoKWRbWUGFL/zIAWgll5QnexoGdKjYg==,iv:Nkyl98g7NkM3+h8jVuNDzg8MgFG2uexPxqwYVLpSo68=,tag:NXdPVnBDDV6I0a4MYlO+qQ==,type:comment]
    #ENC[AES256_GCM,data:E/GX03e+/+dxhUpOl1tySiDOxGDM3aqwMsHrGihEb4J24h6rEBblHSF09+JlJPulsQTprGW8ICGrPPpJVsNfdKm43zQAJ0rptSN0Z6SmD/3XE36sNamsMHZ3fyhsYVs=,iv:IRcbSDuJUGziecVQun0enxEfnkRG8dD7HDv1OqT6sQw=,tag:lYtOtK6DeEoV7fYBcGXiaA==,type:comment]
    #ENC[AES256_GCM,data:90SNvNxizBQdRqYLkkjo7GRGXpF0V+fUHs0Sm3mAwSMBfRYUF9YSv3PbXsaOETSLCD/MdQWxuJcmD+m3JEroDJrWpylYpYcK4zatIGNNjnvKYCXHYA==,iv:rA+CpkpPzrbgbTFoqT04GCWZqjj31zWDvab4zCisR3c=,tag:mlQ575UHRjR7nXZwxjf5lQ==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IUT/nl6RYzsZIovFv3rijNfP,iv:6GShr/TvuX3H23qyYDMF+U2nXg/yGj/zTctWND79lyc=,tag:W15MOzTw4KX2K4yjW/+9vQ==,type:str]
    #ENC[AES256_GCM,data:9NAwkuCY4nUTumxW66bwL2jq0xncj4BnGV0ftscj9MWYJA==,iv:NXUGcUvgMwhf6fbIkfMvfNqe6Ixy+cpLSs+1B7pM/N8=,tag:IE25IZox7aEsUnPmhmning==,type:comment]
    #ENC[AES256_GCM,data:cnQJ8LVStu94O6sIccQCxm/uEZXUVbqyCv9PfYrAjOcI6Ic2x1dfjvCLI1aIlTpiiAYWn9+Tpl+9t2r6Z/z2M97tUrPdEg==,iv:FHT2F5YAlayP8w3nfeQanipyBOX4xSxiIoztLmXDDo0=,tag:Y3dhQXLZao7DlEjsDklsdA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x4/di9yka6Py6z0kuUQ=,iv:v5ItQETrSlELvvvTVfHzntj8+Y33Ihtq+rQlVNifsWc=,tag:hRzim+rPunKa0nFA2aNBCw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2RrVSEhsvEJ5FhZeYqmFAP+EXNfr9J/OIivqWi+MP1MiEpKS+ef0Pw==,iv:wJ0BZUpL+3CoSFapV1UakqqH30u11v+XXwoM0d3pUoU=,tag:Irk57FqwQfvxzpM0TDAwHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T13:00:15Z"
    mac: ENC[AES256_GCM,data:JEMGwurkTV2qTxIEDtCmFmDS4N7UIZju0YEJlgTkXTkkuzUnbmVWzQft6fQr3LabH1WxmzxHJEbDLUAMz6YUUnvGfvaJCzj/+OvmY4EgCmfhyx4i7P5zPhrdFMCDmrNJ8OFR59NyGT8sP1B7zz9Vwj0+zvngwV58x39pnCCd4Wg=,iv:n//t5dtsUhY/vI/cnbl16kXOeAS8FWYG9owUG9JXVp0=,tag:WliWWACGM+MBV5YGygietQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
