# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-ssh
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:/A1yYxa9qXRn2ww=,iv:gAG5T+Cq6iNYiS+pL6wief7HbqdJHnUaQ7Kw4yk6YkA=,tag:01teMCohXIih0Kn4vpxL9g==,type:comment]
    known_hosts: ENC[AES256_GCM,data:TaM3QJ9+rlZkMrcUz0EuGF8uWDuJ/1mLy03+6qYEJold9PYWLwBNJaOfD926FJc22zUphqtDOXMkffbu0t6O1YSV8WhYLROCJLw79b2CZWAK335/DHjDYa62Ki0=,iv:9Bg5ZTmQGgAK7kdSYSbxTi23ks48HK9AjmAPeRd6NmM=,tag:+cs7ei79PhFyQ/YW8M6H4Q==,type:str]
    id_ed25519: ENC[AES256_GCM,data:2PebiM1kiJ2Q4ONgEND3DM7cMYWG3ZHohMxAAJ28D9PJSuoYeOZiKUyF+hjjcomzgCRteGGyYz1+jNvlsJAorTq8iyeAvGK0y9rc2go6v1xQSeLJzjxWl+omeZCTGd5G/SwRN/zyerAU0KdrX++4dcyCeC8cVquBfEN/OXwcFLgM8fT+1GaanlN5d0u+OwYRJAghwtuJSF6eUmSlwwKLAMtQdoIG9QRn5+00l/n/JIilI+PGaKOEs3peANkr+DgxyfVJdsthv9UzQPw8Ojv0jJA0blfpBxNteCDLr3br06omx3799RW+ZlmzLjeBpklXmjK69TG/XiTIRt5mkEh3549dJ2bVzotcuQdeqenbXFZ6tJPs1wbvVUkVR5ssJQj5cAVIgmhu3Gpw8vEwc1iDMB+wgFiZq6Bv05u2aw7jL+2WrI72xy+/F/bt0CslOHa0F12LA1LqhClWOP/wRtklO2MGgTg9f7t0pAWiL17dg841dDjh+r8XlP53SgBUPA7aZieyzIG4xdt6+CEJFwnU2j1TSylyf8wdl5LDKu8V4YiyemWwi+pHcCjpuLE2KVnJtR984jahKPNoUW0MlF3YIhlUuQpSqKAVjkeFF7CxnEGwdZtNFhCxnROwNCGyXRVjdBlF4NBo094E7pAtU8I7Ks7fifE16kAj1VlGbjjI5sRE1UJHUj7O/PH9Qr0IosKtwp9Tfw==,iv:hwst7e2SDdv8LV2LSGVHIaSZoGnVc7ydaB78QcPOP7w=,tag:IVMLGVKd0M1RSBjh+N7Eeg==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:RPODG2lX4AdJxuHTMlP6dgegv6B2JZViKQv71fYKXFPKkXHPwh55qQmQf22XZ2cLlBhHaeBzL7RQjmegj9AftDoFG6KYZhVoITFXbs1+0KBEL8Nu0wj/6x4em9WuoDC1SWnXdXnQKahcRDu4YSEfhu+K9gawW5yC5zVfYHzEtac=,iv:zHO0z5kznh/I7m4jGeMRv6crnQpsmzFwB06/eWWNdzU=,tag:+FzlYXNlkJfqcObdcXWOYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T05:53:25Z"
    mac: ENC[AES256_GCM,data:3p1UBBST6dx4j2Me4xBxLHO65MdhjrDCvX1ZQOOaLNLv+ZpgGg2484dOaCTwHkNemoR6gN27NH8VuPY/sPw3uk4XhUEA8cCRPngAYSj9AmRkqEJNNCjZg2IjlGOkopWY6rcHzoJvjteBfjNHqXQURYa2CtKkDIGGzm2oYhkhshQ=,iv:NWcsDLBWPQ/CrVS2pz9yQOecpGi28MwxkEmzEE8QlDY=,tag:YP0mOoIpxO5Xs84kvk7vNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-restic-secret
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PWVk8p/tDrTsCATUYTjrvn5jdXRXzTQujeLp1HxDS/VSDd0phnU4vOvB89oJ38+rWAhkJo2+TlUbDM74mIPkufdodIav9a8O1uMkExwLKk/g,iv:Udn4aZ3Qv26hsLN8gwPjIc/WbmZ1OD5d/eBUoxENwRk=,tag:dafG1Er2wXtIeYS8CwFvDw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ErDtgNQaOXWfzk5+0b7P+BKaRVGG9EoAHrOnm7mMqZdmBuj/H3x48VuWOw==,iv:A3gqe7cwgIh1qty2Goua3Q4WOmt0MqpYmoCLCNTj5LA=,tag:E0PV++W8GJEm2/w3i5dMGg==,type:str]
    #ENC[AES256_GCM,data:pQWk7bQSBQhI5vkhFcosRY5Q5unXCyu5qNGj7jf9vxWxzVSZ7KyyVAFntpTo1jLEMDIBwuGgh8cuRE8XEx2Zm0lNpwIdAY3vvLI3hidWoKWRbWUGFL/zIAWgll5QnexoGdKjYg==,iv:Nkyl98g7NkM3+h8jVuNDzg8MgFG2uexPxqwYVLpSo68=,tag:NXdPVnBDDV6I0a4MYlO+qQ==,type:comment]
    #ENC[AES256_GCM,data:E/GX03e+/+dxhUpOl1tySiDOxGDM3aqwMsHrGihEb4J24h6rEBblHSF09+JlJPulsQTprGW8ICGrPPpJVsNfdKm43zQAJ0rptSN0Z6SmD/3XE36sNamsMHZ3fyhsYVs=,iv:IRcbSDuJUGziecVQun0enxEfnkRG8dD7HDv1OqT6sQw=,tag:lYtOtK6DeEoV7fYBcGXiaA==,type:comment]
    #ENC[AES256_GCM,data:90SNvNxizBQdRqYLkkjo7GRGXpF0V+fUHs0Sm3mAwSMBfRYUF9YSv3PbXsaOETSLCD/MdQWxuJcmD+m3JEroDJrWpylYpYcK4zatIGNNjnvKYCXHYA==,iv:rA+CpkpPzrbgbTFoqT04GCWZqjj31zWDvab4zCisR3c=,tag:mlQ575UHRjR7nXZwxjf5lQ==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:IUT/nl6RYzsZIovFv3rijNfP,iv:6GShr/TvuX3H23qyYDMF+U2nXg/yGj/zTctWND79lyc=,tag:W15MOzTw4KX2K4yjW/+9vQ==,type:str]
    #ENC[AES256_GCM,data:9NAwkuCY4nUTumxW66bwL2jq0xncj4BnGV0ftscj9MWYJA==,iv:NXUGcUvgMwhf6fbIkfMvfNqe6Ixy+cpLSs+1B7pM/N8=,tag:IE25IZox7aEsUnPmhmning==,type:comment]
    #ENC[AES256_GCM,data:cnQJ8LVStu94O6sIccQCxm/uEZXUVbqyCv9PfYrAjOcI6Ic2x1dfjvCLI1aIlTpiiAYWn9+Tpl+9t2r6Z/z2M97tUrPdEg==,iv:FHT2F5YAlayP8w3nfeQanipyBOX4xSxiIoztLmXDDo0=,tag:Y3dhQXLZao7DlEjsDklsdA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:x4/di9yka6Py6z0kuUQ=,iv:v5ItQETrSlELvvvTVfHzntj8+Y33Ihtq+rQlVNifsWc=,tag:hRzim+rPunKa0nFA2aNBCw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2RrVSEhsvEJ5FhZeYqmFAP+EXNfr9J/OIivqWi+MP1MiEpKS+ef0Pw==,iv:wJ0BZUpL+3CoSFapV1UakqqH30u11v+XXwoM0d3pUoU=,tag:Irk57FqwQfvxzpM0TDAwHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T05:53:25Z"
    mac: ENC[AES256_GCM,data:3p1UBBST6dx4j2Me4xBxLHO65MdhjrDCvX1ZQOOaLNLv+ZpgGg2484dOaCTwHkNemoR6gN27NH8VuPY/sPw3uk4XhUEA8cCRPngAYSj9AmRkqEJNNCjZg2IjlGOkopWY6rcHzoJvjteBfjNHqXQURYa2CtKkDIGGzm2oYhkhshQ=,iv:NWcsDLBWPQ/CrVS2pz9yQOecpGi28MwxkEmzEE8QlDY=,tag:YP0mOoIpxO5Xs84kvk7vNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
