# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-ssh
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:/A1yYxa9qXRn2ww=,iv:gAG5T+Cq6iNYiS+pL6wief7HbqdJHnUaQ7Kw4yk6YkA=,tag:01teMCohXIih0Kn4vpxL9g==,type:comment]
    known_hosts: ENC[AES256_GCM,data:TaM3QJ9+rlZkMrcUz0EuGF8uWDuJ/1mLy03+6qYEJold9PYWLwBNJaOfD926FJc22zUphqtDOXMkffbu0t6O1YSV8WhYLROCJLw79b2CZWAK335/DHjDYa62Ki0=,iv:9Bg5ZTmQGgAK7kdSYSbxTi23ks48HK9AjmAPeRd6NmM=,tag:+cs7ei79PhFyQ/YW8M6H4Q==,type:str]
    id_ed25519: ENC[AES256_GCM,data:2PebiM1kiJ2Q4ONgEND3DM7cMYWG3ZHohMxAAJ28D9PJSuoYeOZiKUyF+hjjcomzgCRteGGyYz1+jNvlsJAorTq8iyeAvGK0y9rc2go6v1xQSeLJzjxWl+omeZCTGd5G/SwRN/zyerAU0KdrX++4dcyCeC8cVquBfEN/OXwcFLgM8fT+1GaanlN5d0u+OwYRJAghwtuJSF6eUmSlwwKLAMtQdoIG9QRn5+00l/n/JIilI+PGaKOEs3peANkr+DgxyfVJdsthv9UzQPw8Ojv0jJA0blfpBxNteCDLr3br06omx3799RW+ZlmzLjeBpklXmjK69TG/XiTIRt5mkEh3549dJ2bVzotcuQdeqenbXFZ6tJPs1wbvVUkVR5ssJQj5cAVIgmhu3Gpw8vEwc1iDMB+wgFiZq6Bv05u2aw7jL+2WrI72xy+/F/bt0CslOHa0F12LA1LqhClWOP/wRtklO2MGgTg9f7t0pAWiL17dg841dDjh+r8XlP53SgBUPA7aZieyzIG4xdt6+CEJFwnU2j1TSylyf8wdl5LDKu8V4YiyemWwi+pHcCjpuLE2KVnJtR984jahKPNoUW0MlF3YIhlUuQpSqKAVjkeFF7CxnEGwdZtNFhCxnROwNCGyXRVjdBlF4NBo094E7pAtU8I7Ks7fifE16kAj1VlGbjjI5sRE1UJHUj7O/PH9Qr0IosKtwp9Tfw==,iv:hwst7e2SDdv8LV2LSGVHIaSZoGnVc7ydaB78QcPOP7w=,tag:IVMLGVKd0M1RSBjh+N7Eeg==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:RPODG2lX4AdJxuHTMlP6dgegv6B2JZViKQv71fYKXFPKkXHPwh55qQmQf22XZ2cLlBhHaeBzL7RQjmegj9AftDoFG6KYZhVoITFXbs1+0KBEL8Nu0wj/6x4em9WuoDC1SWnXdXnQKahcRDu4YSEfhu+K9gawW5yC5zVfYHzEtac=,iv:zHO0z5kznh/I7m4jGeMRv6crnQpsmzFwB06/eWWNdzU=,tag:+FzlYXNlkJfqcObdcXWOYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:30:39Z"
    mac: ENC[AES256_GCM,data:kqkYNftkQyDVNWc1jEY4YFCcBApa4/OWOIPuRMyPFqNx00tyU5LgAZnAkH8EOLTfQ1oUBiiQRsRMCL0Jgv0F2FbyT+PMKMgoEH/YrIGHkatZCsqq6176NYLBDzUthKr1Dxzdy1SDvUKfH06GBbHW0N2mnRd0u8d+qJX02hZdNe8=,iv:JDMpxyBDDlwnrcQ/fUdIF1j9GgluFEp/ksl7p070ro0=,tag:6SqRRkC14RwiEAbqzKn88Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
