# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-ssh
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:/A1yYxa9qXRn2ww=,iv:gAG5T+Cq6iNYiS+pL6wief7HbqdJHnUaQ7Kw4yk6YkA=,tag:01teMCohXIih0Kn4vpxL9g==,type:comment]
    #ENC[AES256_GCM,data:ZQesWbP3tA9Z0Ctnr42W,iv:EsizZeD3/1cugQgBnCW2nLKAkknO0CrMBXzxD9l1iM4=,tag:/8qGbaMBUV7/aTMRyPkaDA==,type:comment]
    #ENC[AES256_GCM,data:h8m2PH5lUexfMRpmcmzEB4eUeI3LpQs9VdJq/myE6TRm38hc+hUDdiz3lOcxHABFa77u2cvcUSOWnrf0iJ4oYGuZRp072aQQVLVBkV9S3vtNT4KrFVcOzwQSsUTPCSXK,iv:H4W+ulknJ3aYm8cvTaP2nLFyuXF74ud1z1nhxJGsUog=,tag:MuEv73Fbq6On09oBbyU4Ag==,type:comment]
    id_ed25519: ENC[AES256_GCM,data:ka9zQM7V2y2mzL/tvYcDOh1tzQV/eMcJ1x5Hhq9neMW3Fd3fuGbobp9r1KCuepuFIR4WGeoYPTxW2DWr68NEdGc0lMPkYiy8CkRXpHaQYfoEgB83tQ7M9EYj5Sq+RxiyenzzIET+obH97iscSpx+Ud4gOV8Fpdfe7d0608w8WSeiSo8U+bZLv5YucgDapKXYpBaIC+spWIZoZxTT3XhL54/PWhjM0RBAUV1Wya+2xPBdmPuyaFddyyr5FiA+XOPNlUwLvuF34V+Ilnvkyt/FqbE5Q4xZDIspRJtDOC/PBu9zOonyK3t3gQzN1otxNuIpl5eyvhH/2O9X/NbF0fAfd1ulUSpS2hXXNcZfckerWZCq5/4g15Au2W3cwhklqL49fg9V2X6zviT1A9AFDM1nZMkgr9rDK7yQFEYFPMl7xkO/hj9DDeZKjj999whXP4/05tj8ebdULOiZNmHet7TKlLy51ebU+Z7un8+oyiiSHoiAwgPb+/5LoNOYvus8V7yFrKIEw5MnsMw=,iv:sRnN0XxaImkMUrGCS8ihhBh6QlRei0UmocP6pVKrb1A=,tag:AZyh9+qtKnsrgSXTFNX8RQ==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:e1cJlBY2eISj2xUpfet1mIxIHTfpr/q+0Almzd8TPpn4xmj+/46jcqMiE0FbYSDxZScSFn7YFnSnD55W6BVR8HeET+dgpBfD7BC8YLBpBH9RmzewodLiS1ynWur0AQ==,iv:2xEUsZ8CtXjmQ7d6N6DroJKKXsOaQUJyOWxiLf15QPM=,tag:ICr0hwtGSiCY+8uPEWooZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:58:07Z"
    mac: ENC[AES256_GCM,data:VZaBSCZQGcnrWghMPPAqhHX+hu9f5lTJDSC8kPqjIpf8yp7JGN+qStq8ed/JP3hfAWy9WTN40H73e9UBrH0bwW6GnZNR+vMfvFVL+W4QYy6CgQeE5mIdenosbgbPatz/mwAk+dYItvjZYBz/U3779+/lLEVT+zWiwOxJaJnDpgc=,iv:xCnCW5daOEpF5SRmaM710lntylTE6eeNZYu3t6VvCqs=,tag:VopAz3UDjlaRwvfDj3ijSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
