# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-ssh
    namespace: home-automation
stringData:
    #ENC[AES256_GCM,data:/A1yYxa9qXRn2ww=,iv:gAG5T+Cq6iNYiS+pL6wief7HbqdJHnUaQ7Kw4yk6YkA=,tag:01teMCohXIih0Kn4vpxL9g==,type:comment]
    #ENC[AES256_GCM,data:ZQesWbP3tA9Z0Ctnr42W,iv:EsizZeD3/1cugQgBnCW2nLKAkknO0CrMBXzxD9l1iM4=,tag:/8qGbaMBUV7/aTMRyPkaDA==,type:comment]
    #ENC[AES256_GCM,data:h8m2PH5lUexfMRpmcmzEB4eUeI3LpQs9VdJq/myE6TRm38hc+hUDdiz3lOcxHABFa77u2cvcUSOWnrf0iJ4oYGuZRp072aQQVLVBkV9S3vtNT4KrFVcOzwQSsUTPCSXK,iv:H4W+ulknJ3aYm8cvTaP2nLFyuXF74ud1z1nhxJGsUog=,tag:MuEv73Fbq6On09oBbyU4Ag==,type:comment]
    id_ed25519: ENC[AES256_GCM,data:2PebiM1kiJ2Q4ONgEND3DM7cMYWG3ZHohMxAAJ28D9PJSuoYeOZiKUyF+hjjcomzgCRteGGyYz1+jNvlsJAorTq8iyeAvGK0y9rc2go6v1xQSeLJzjxWl+omeZCTGd5G/SwRN/zyerAU0KdrX++4dcyCeC8cVquBfEN/OXwcFLgM8fT+1GaanlN5d0u+OwYRJAghwtuJSF6eUmSlwwKLAMtQdoIG9QRn5+00l/n/JIilI+PGaKOEs3peANkr+DgxyfVJdsthv9UzQPw8Ojv0jJA0blfpBxNteCDLr3br06omx3799RW+ZlmzLjeBpklXmjK69TG/XiTIRt5mkEh3549dJ2bVzotcuQdeqenbXFZ6tJPs1wbvVUkVR5ssJQj5cAVIgmhu3Gpw8vEwc1iDMB+wgFiZq6Bv05u2aw7jL+2WrI72xy+/F/bt0CslOHa0F12LA1LqhClWOP/wRtklO2MGgTg9f7t0pAWiL17dg841dDjh+r8XlP53SgBUPA7aZieyzIG4xdt6+CEJFwnU2j1TSylyf8wdl5LDKu8V4YiyemWwi+pHcCjpuLE2KVnJtR984jahKPNoUW0MlF3YIhlUuQpSqKAVjkeFF7CxnEGwdZtNFhCxnROwNCGyXRVjdBlF4NBo094E7pAtU8I7Ks7fifE16kAj1VlGbjjI5sRE1UJHUj7O/PH9Qr0IosKtwp9Tfw==,iv:hwst7e2SDdv8LV2LSGVHIaSZoGnVc7ydaB78QcPOP7w=,tag:IVMLGVKd0M1RSBjh+N7Eeg==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:RPODG2lX4AdJxuHTMlP6dgegv6B2JZViKQv71fYKXFPKkXHPwh55qQmQf22XZ2cLlBhHaeBzL7RQjmegj9AftDoFG6KYZhVoITFXbs1+0KBEL8Nu0wj/6x4em9WuoDC1SWnXdXnQKahcRDu4YSEfhu+K9gawW5yC5zVfYHzEtac=,iv:zHO0z5kznh/I7m4jGeMRv6crnQpsmzFwB06/eWWNdzU=,tag:+FzlYXNlkJfqcObdcXWOYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T06:53:28Z"
    mac: ENC[AES256_GCM,data:C704UJkRYcpEhFxPoPH93fS+l2Xv6AyV2IKKZhhLeIYr0N5r5DoI1fuB+H0edcgiHf5tMekgymuMebawT+pGmFoBYDIBU1Z8o3cmJdeDLU5luKik2MXhkTTLFo6Y+CL+f/7BVPzMStGMGCQAdKZswHRcua1b+TE3vfiDplW1CJI=,iv:Lg4YSuFV51ryDLDA3FOcfCneFukKXq0VlhSrVuSQvR4=,tag:o23kqRxf6bEeUqcpG9RGmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
