---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  sourcePVC: config-home-assistant-0
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: home-assistant-restic-secret
    retain:
      daily: 14
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: longhorn
    cacheStorageClassName: local-hostpath
