---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot 
    repository: home-assistant-restic-secret
    cacheStorageClassName: "ceph-block"
    cacheAccessModes: [ReadWriteOnce]
    cacheCapacity: "8Gi"
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "home-assistant-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: home-assistant-restic-secret
    cacheStorageClassName: ceph-block
    cacheCapacity: 8Gi
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    accessModes:
      - ReadWriteOnce
    capacity: 5Gi

