---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: home-assistant-restic-secret
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
    cacheStorageClassName: "openebs-hostpath"
    cacheCapacity: "1Gi"
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    retain:
      hourly: 24
      daily: 7
      weekly: 5
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "home-assistant-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    copyMethod: Snapshot
    repository: home-assistant-restic-secret
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
    accessModes:
      - ReadWriteOnce
    capacity: 5Gi

