---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant
  namespace: home
spec:
  sourcePVC: home-assistant-config
  trigger:
    schedule: "0 */12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: home-assistant-restic-secret
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    cacheStorageClassName: "local-hostpath"
    cacheCapacity: "1Gi"
    storageClassName: "ceph-block"
    volumeSnapshotClassName: "csi-ceph-blockpool"
    retain:
      hourly: 24
      daily: 7
      weekly: 5
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
# apiVersion: volsync.backube/v1alpha1
# kind: ReplicationDestination
# metadata:
#   name: "home-assistant-bootstrap"
# spec:
#   trigger:
#     manual: restore-once
#   restic:
#     copyMethod: Snapshot
#     repository: home-assistant-restic-secret
#     cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-local-hostpath}"
#     cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-8Gi}"
#     storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
#     volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
#     moverSecurityContext:
#       runAsUser: 0
#       runAsGroup: 0
#       fsGroup: 0
#     accessModes:
#       - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
#     capacity: "${VOLSYNC_CAPACITY:-5Gi}"

