apiVersion: v1
kind: Secret
metadata:
    name: thanos-secret
    namespace: monitoring
stringData:
    S3_BUCKET_NAME: thanos
    S3_BUCKET_HOST: minio.default:9000
    S3_BUCKET_REGION: us-east-1
    S3_ACCESS_KEY: thanos
    S3_SECRET_KEY: Sgo2ozmR39XpSCBg44iosI90sc7LoIqF
type: Opaque
