---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-opnsense
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns-bind
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: externaldns-bind
            key: externaldns-secret
    extraArgs:    
      - --rfc2136-host=10.11.0.1
      - --rfc2136-port=5353
      - --rfc2136-zone=f-wi.com
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-keyname=rndc-key
      - --rfc2136-tsig-axfr
    policy: sync
    sources:
      - gateway-httproute
      - service
    registry: noop
    domainFilters:
      - f-wi.com
    txtPrefix: external-dns-
    txtOwnerId: k8s
    serviceMonitor:
      enabled: true
