---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app externaldns-bind
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: externaldns-bind
            key: externaldns-secret
    extraArgs:
      - --ingress-class=internal
      - --rfc2136-host=10.10.0.2
      - --rfc2136-port=53
      - --rfc2136-zone=f-wi.com
      - --rfc2136-tsig-secret-alg=hmac-sha256
      - --rfc2136-tsig-key=externaldns
      - --rfc2136-tsig-axfr
    policy: upsert-only
    sources: ["crd", "ingress","service"]
    txtPrefix: external-dns-
    txtOwnerId: k8s
    domainFilters: ["${SECRET_DOMAIN}"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: externaldns-bind
