apiVersion: v1
kind: Secret
metadata:
    name: externaldns-bind
stringData:
    externaldns-secret: ENC[AES256_GCM,data:eFvlMMjqLkDmkvvFrOAzlR8VJwLNAcM4IEqFfpi4/Y4cooxhJrk9POW5PmY=,iv:cTw06giZ2slUIwvTgCCwp7KftAOZ0dTIz+QusFi4+8Y=,tag:s+xGiK0EoESrzqaBh3dfLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqM1RaZkVZaWt2YkpPZVNl
            VEJOZHMzTEJUWnFqNmloYm5rVVZTaGs0UzBRCndGUEZPSnhYdk5RYXVsR04vdFBn
            UVloN1hPcWR3TXliVVhhVGxzTVUvbHcKLS0tIDJoaXl6aFplTksxamh2YzcxSUNw
            dmtuYUhBU1k4aXBMYXRXak5IbnU3WjQKs5B4i9TXWQ0GiTB9FR6hBcfToqjI4teZ
            u16YG3RRRby7y25/pE6tetJVKwgeVYmMKRFKrb2dDikckPeJJLvong==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T05:36:21Z"
    mac: ENC[AES256_GCM,data:HIL69a3RjMK0nNT/pQlUS3pgeEsNUXd7Sekd+qPKY9zOOtkWlC0hu8Dy0o6VsC3ioSsBo+c3xxuUKpPzRPBkRT4ShVXTtkOsXb9iO05x60UbDSgT6TxZBzlibS7WqbIVQdVEc43ceQPA264zGYQ5VtCJHMYTh+um/vKYxsW26vQ=,iv:5ybSIRdoxcEn6qkLon7mhq7Ir4wMej0Z9o8hUtdrOAM=,tag:5Lajzr24R1H/D9HP0k8Ghw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
