---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: omada-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/charlie-haley/omada_exporter
      tag: 0.10.0

    env:
      OMADA_HOST: "${LOCAL_LAN_OMADA}"
      OMADA_USER: exporter
      OMADA_PASS:
        valueFrom:
          secretKeyRef:
            name: omada-exporter-secret
            key: omada_exporter_password
      OMADA_SITE: Standard

    service:
      main:
        ports:
          http:
            port: 9202

    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 5s

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
