apiVersion: v1
kind: Secret
metadata:
    name: omada-exporter-secret
    namespace: monitoring
stringData:
    omada_exporter_password: ENC[AES256_GCM,data:0v+ytxweFuAzzfybf7GMOgj3,iv:pjI7iVxPniV6g83HwskQB1Lte0HWCuirb30swx+u770=,tag:RYLMoRylNRzmS8t6K9PHrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bnZGQkdOcDFyRVZSeHlV
            R0VteHo0VGVaSGpZdGlmeE1jWXJnTGp0YVZNClZXSW5mYUd0WXZLVi93NmNQakFE
            MEV0Q2FtdkZqUVVQNzdmZW5zSVo5d0UKLS0tIEdGbG1KUndRSkk5WnhYRmpycms2
            NDFVR3VWVGhsMlJCRVZySk9McHNMU00KWn35quffSZ/6J2MLCDikfcrQJH+9zRmU
            FOqsB+gyxlsMCgCW3i3SQfeACx4+P1259mOfAOmtXeoXXndXSMADcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T05:02:39Z"
    mac: ENC[AES256_GCM,data:6G9hoAxg1cIjXOdqI4vuTDPchbd2a/l6q6W399d8adA41A/9xhYPPfZxBSoRzeAukv2j2zQy5t05CUHQAEpL4+sc3r7dVUT5MA2hIdtHgu6elVQhEP+VZ/yVwheCxu8RfElFAVg4Lzm0lFBoSf7zfhkniO0cq7dYks5XqKwuLVk=,iv:pyV2vIuN5T7wVVgkiZU5ORC/flsNFVsDLkC+IOXVenw=,tag:RPCt+TJBeUA68rC84WMdnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
