---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app paperless
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.17

    envFrom:
      - secretRef:
          name: *app
      - configMapRef:
          name: paperless-configmap

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "note-multiple"
        hosts:
          - host: &host "dms.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      nas-consume:
        enabled: true
        mountPath: /data/nas/consume
        readonly: false
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        path: /mnt/Volume1/document/scan
      nas-export:
        enabled: true
        mountPath: /data/nas/export
        readonly: false
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        path: /mnt/Volume1/document/export

    resources:
      requests:
        cpu: 11m
        memory: 1812M
      limits:
        memory: 1812M

    volumeClaimTemplates:
      - name: data
        mountPath: /data/local
        accessMode: ReadWriteOnce
        size: 15Gi
        storageClass: ceph-block
