---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./pvc.yaml
  - ./secret.sops.yaml
  # - ./helmrelease.yaml
  # - ./volsync.yaml
labels:
  - pairs:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/part-of: paperless
