---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "paperless-data"
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "paperless-bootstrap"
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-block
