---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "paperless-data"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:-ReadWriteOnce}"
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "paperless-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:-1Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:-ceph-block}"
