apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:JCxv0KlN0PO6hi6NuUb5jnFfqB6xcG4lUGVEF/BnAdwG1P8K,iv:iFMXMVIMaswsPTLyPmdttUZzfPPOTekp3UUDo/nBX9s=,tag:TlbxDCmdPbqt34oIeRmmWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:pe0f64oX3Rnf12KA64GKxYRKwMkgRdB20QnOEjFJipp2x/a02lZROQmNVVl7gvvKtFQGwpB6D1P3YXQyJ6bBk2Cu5kPyGNF3tUQbZkEXQzBFO7h/3FGx/mg5IEAWanijpUbrC5/1D85ca98WYLsLWrGzUz8W/lb4x6jOP++aaf4pp/LO5cq1ldIuRPlFFRmlGzNrl3p+qN0ai4zN/7KixI3DTIW46YbUSGtEC1tLaA==,iv:2qzDXfOqna9jzwa62jILaZLUF64ZWfsCXZTS8vM+Qik=,tag:ZSgJP8/MfH3L7cUkMOHQhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bnZGQkdOcDFyRVZSeHlV
            R0VteHo0VGVaSGpZdGlmeE1jWXJnTGp0YVZNClZXSW5mYUd0WXZLVi93NmNQakFE
            MEV0Q2FtdkZqUVVQNzdmZW5zSVo5d0UKLS0tIEdGbG1KUndRSkk5WnhYRmpycms2
            NDFVR3VWVGhsMlJCRVZySk9McHNMU00KWn35quffSZ/6J2MLCDikfcrQJH+9zRmU
            FOqsB+gyxlsMCgCW3i3SQfeACx4+P1259mOfAOmtXeoXXndXSMADcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T08:36:57Z"
    mac: ENC[AES256_GCM,data:uNBFuFLPEfES1LYgjoJjvt6a8j1C+ILqejqyWqYWTVBWqnHjak456GPQ9BK8AAJWhmq86jr7dj9hsLdthDks3dEbhZztrFj9llhsmHfhSXXsoAK+Xy+pCTrdtvSxPI18pnv6ZEYOfKpEv5qPn1yHDPUsK3toRBo9xgsUK80Xnrs=,iv:EDxT1bk3yWA3H0yrvsmZRNf1L5PBgD3ewKfH+RXwpb8=,tag:o69/hA7pAu/bgqvc3xhgBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
