---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: dragonfly
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: dragonfly
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: 2m
    storage:
      enabled: true
      requests: 128Mi # Set as desired

    extraArgs:
      - --dbfilename=dump.rdb
      - --save_schedule=*:* # HH:MM glob format

    podSecurityContext:
      fsGroup: 2000

    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      spec:
        - alert: DragonflyMissing
          expr: absent(dragonfly_uptime_in_seconds) == 1
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Dragonfly is missing
            description: "Dragonfly is missing"
