---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ser2sock
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: tenstartups/ser2sock
      tag: latest
    env:
      # -- Port where ser2sock listens
      LISTENER_PORT: 10000
      # -- Path to the serial device
      SERIAL_DEVICE: /dev/ttyUSB0
      # -- Serial device baud rate
      BAUD_RATE: 115200
    service:
      main:
        ports:
          http:
            enabled: false
          server:
            enabled: true
            protocol: TCP
            port: 10000

    ingress:
      main:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
