# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ser2sock
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      ser2sock:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: ser2sock
            # -- Image repository and tag for the ser2sock application.
            # @default -- See values.yaml
            image:
              repository: tenstartups/ser2sock
              tag: latest
            env:
              # -- Port where ser2sock listens
              LISTENER_PORT: 10000
              # -- Path to the serial device
              SERIAL_DEVICE: /dev/ttyUSB0
              # -- Serial device baud rate
              BAUD_RATE: 115200
    service:
      app:
        ports:
          http:
            enabled: false
            port: 80
          server:
            enabled: true
            protocol: TCP
            port: 10000
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml
      usb:
        enabled: true
        type: hostPath   
        hostPathType: CharDevice
        hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231120161348-if00
        advancedMounts:
          ser2sock:
            app:
              - path: /dev/ttyUSB0
              
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged:  true

    # -- Affinity constraint rules to place the Pod on a specific node.
    # [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/usb-ff_10c4_ea60.present
              operator: In
              values:
              - "true"
