---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./volsync.yaml
commonLabels:
  app.kubernetes.io/name: ser2sock
  app.kubernetes.io/instance: ser2sock
