---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname zigbee2mqtt
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/home-automation/zigbee2mqtt/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: system
    - name: mosquitto
      namespace: home-automation
    - name: onepassword-store
      namespace: external-secrets
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: zigbee2mqtt-data