---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zigbee2mqtt
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/home-automation/zigbee2mqtt/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-mosquitto
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-ser2sock
