---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template

  values:
    controllers:
      echo-server:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 38
            env:
              HTTP_PORT: &port 8080
              LOG_WITHOUT_NEWLINE: "true"
              LOG_IGNORE_PATH: "/healthz"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 64M
              limits:
                memory: 64M

    service:
      app:
        ports:
          http:
            port: *port

    route:
      external:
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target:  echo-server.f-wi.com
        hostnames:
          - echo-server.f-wi.com
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port