---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: volsync
  dependsOn:
    - name: openebs
      namespace: system
    - name: snapshot-controller
      namespace: system
  values:
    manageCRDs: true
    metrics:
      disableAuth: true