---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false          
          keep: false

    zfs-localpv:
      enabled: false

    lvm-localpv:
      enabled: false

    mayastor:
      enabled: false
    localpv-provisioner:
      rbac:
        create: true
      localpv:
        image:
          registry: quay.io/
          repository: openebs/provisioner-localpv
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: /var/openebs/local
