---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.11.0.0/24"