---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: 10.11.0.50
      stop: 10.11.0.150