---
# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.f-wi.com"
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "10.11.0.202"
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "external.f-wi.com"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.f-wi.com"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.f-wi.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: f-wi-com-production-tls
