---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "f-wi.com"
  dnsNames:
    - "f-wi.com"
    - "*.f-wi.com"
