---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/flux/globals
  - ../../components/flux/sops
#   - ../../components/flux/alerts
  - ../../components/repos/app-template
resources:
  - ./namespace.yaml  
  - ./external-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./gateway-api/ks.yaml
  
